import { AlertTriangle, ArrowLeft, BrainCircuit, ChevronDown, ChevronUp, Database, ExternalLink, FileSearch, RefreshCw, ShieldCheck } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { AnalysisProgress } from "../../components/analytics/AnalysisProgress";
import { analyzeAnalyticsDataset, getAnalyticsDataset, getAnalyticsDatasetStatus, getAnalyticsPreview, getAnalyticsProfile, listAnalyticsDashboards, refreshAnalyticsDataset } from "../../services/api";
import { useAdminStore } from "../../store/admin.store";
import type { AnalyticsColumn, AnalyticsDataset, AnalyticsStatus } from "../../types/analytics";
import { formatTableValue } from "../../utils/analytics-format";

export function AdminAnalyticsDatasetDetailPage(){
  const{id}=useParams();const csrf=useAdminStore(state=>state.csrfToken);const[dataset,setDataset]=useState<AnalyticsDataset|null>(null);const[status,setStatus]=useState<AnalyticsStatus|null>(null);const[columns,setColumns]=useState<AnalyticsColumn[]>([]);const[rows,setRows]=useState<Array<{rowNumber:number;data:Record<string,unknown>}>>([]);const[profile,setProfile]=useState<{duplicateRowCount:number;profile:Record<string,unknown>;dataQualityWarnings:unknown[]}|null>(null);const[dashboardId,setDashboardId]=useState<string|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[refreshFile,setRefreshFile]=useState<File|null>(null);const[showPreview,setShowPreview]=useState(false);const[showWarnings,setShowWarnings]=useState(false);const[previewLoading,setPreviewLoading]=useState(false);
  const load=useCallback(async()=>{if(!id)return;setLoading(true);try{const[datasetResponse,statusResponse]=await Promise.all([getAnalyticsDataset(id),getAnalyticsDatasetStatus(id)]);setDataset(datasetResponse.dataset);setStatus(statusResponse);if(["PROFILING","ANALYZING","GENERATING","READY"].includes(statusResponse.status)){try{const response=await getAnalyticsProfile(id);setProfile(response.profile)}catch{/* Profile is not ready yet. */}}const dashboards=await listAnalyticsDashboards(1,100);setDashboardId(dashboards.dashboards.find(item=>item.dataset.id===id)?.id??null)}catch(value){setError(value instanceof Error?value.message:"Unable to load dataset")}finally{setLoading(false)}},[id]);
  useEffect(()=>{void load()},[load]);useEffect(()=>{if(!id||status?.status==="READY")return;const timer=window.setInterval(()=>void load(),1500);return()=>window.clearInterval(timer)},[id,load,status?.status]);
  async function analyze(){if(!csrf||!id)return;await analyzeAnalyticsDataset(csrf,id);await load()}
  async function refreshSource(){if(!csrf||!id||!refreshFile)return;await refreshAnalyticsDataset(csrf,id,refreshFile);setRefreshFile(null);setShowPreview(false);await load()}
  async function togglePreview(){if(showPreview){setShowPreview(false);return}if(!id)return;setPreviewLoading(true);try{const response=await getAnalyticsPreview(id,1,15);setColumns(response.columns);setRows(response.rows);setShowPreview(true)}catch(value){setError(value instanceof Error?value.message:"Unable to load preview")}finally{setPreviewLoading(false)}}
  if(loading&&!dataset)return <main className="grid min-h-[70vh] place-items-center"><RefreshCw className="size-8 animate-spin text-primary"/></main>;
  if(!dataset||!status)return <main className="p-10 text-center text-error">{error||"Dataset unavailable"}</main>;
  const compact=profile?.profile as {completenessPercentage?:number;typeSummary?:Record<string,number>}|undefined;const warnings=profile?.dataQualityWarnings??[];
  return <main className="px-4 py-7 sm:px-6 lg:px-8 lg:py-10"><div className="mx-auto max-w-7xl"><Link className="inline-flex items-center gap-2 text-sm font-semibold text-primary" to="/analytics/datasets"><ArrowLeft className="size-4"/>My datasets</Link><div className="mt-5"><AnalysisProgress status={status}/></div>
    {error?<p className="mt-4 rounded-xl bg-negative-soft p-4 text-sm text-error">{error}</p>:null}
    <div className="mt-6 grid gap-4 grid-cols-2 lg:grid-cols-4">{[["Rows",dataset.rowCount.toLocaleString("en-IN")],["Columns",String(dataset.columnCount)],["Completeness",compact?.completenessPercentage!==undefined?`${compact.completenessPercentage}%`:"—"],["Duplicates",String(profile?.duplicateRowCount??"—")]].map(([label,value])=><div className="analytics-panel p-4 sm:p-5" key={label}><p className="text-xs uppercase tracking-wide text-text-secondary">{label}</p><p className="mt-2 font-heading text-xl font-semibold sm:text-2xl">{value}</p></div>)}</div>
    {status.status==="ANALYZING"&&status.semanticModelVersion===0?<button className="mt-6 inline-flex min-h-12 items-center gap-2 rounded-xl bg-primary px-6 font-semibold text-white" onClick={()=>void analyze()} type="button"><BrainCircuit className="size-5"/>Start AI analysis</button>:null}
    <section className="analytics-panel mt-6 flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:p-5"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-brand-soft text-primary"><Database className="size-5"/></span><div><p className="font-semibold">Refresh source data</p><p className="text-xs leading-5 text-text-secondary">Creates a new immutable dataset and profile version. Semantic analysis remains separately governed.</p></div><input accept=".csv,.xlsx,.xls" className="text-sm sm:ml-auto sm:max-w-56" onChange={event=>setRefreshFile(event.target.files?.[0]??null)} type="file"/><button className="action-btn justify-center" disabled={!refreshFile} onClick={()=>void refreshSource()} type="button">Refresh source</button></section>
    {dashboardId?<Link className="mt-6 inline-flex min-h-12 items-center gap-2 rounded-xl bg-forest px-6 font-semibold text-white" to={`/analytics/dashboards/${dashboardId}`}>Open analytics dashboard<ExternalLink className="size-4"/></Link>:null}
    <section className="analytics-panel mt-6 overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-outline p-5"><div className="flex items-center gap-3"><span className={`grid size-9 place-items-center rounded-lg ${warnings.length?"bg-warning-soft text-warning":"bg-positive-soft text-success"}`}>{warnings.length?<AlertTriangle className="size-4"/>:<ShieldCheck className="size-4"/>}</span><div><h2 className="font-heading text-lg font-semibold">Data quality summary</h2><p className="text-xs text-text-secondary">{warnings.length?`${warnings.length} quality observation${warnings.length===1?"":"s"} detected`:"No blocking quality issues detected"}</p></div></div>{warnings.length?<button className="inline-flex min-h-9 items-center gap-1 text-xs font-semibold text-primary" onClick={()=>setShowWarnings(!showWarnings)} type="button">{showWarnings?"Hide details":"Review details"}{showWarnings?<ChevronUp className="size-4"/>:<ChevronDown className="size-4"/>}</button>:null}</div>{showWarnings?<div className="grid gap-2 p-4 sm:grid-cols-2">{warnings.slice(0,20).map((warning,index)=>{const value=warning&&typeof warning==="object"&&!Array.isArray(warning)?warning as Record<string,unknown>:null;return <article className="rounded-lg border border-outline p-3" key={index}><p className="text-xs font-semibold">{String(value?.code??value?.type??`Observation ${index+1}`)}</p><p className="mt-1 text-xs leading-5 text-text-secondary">{String(value?.message??value?.description??warning)}</p></article>})}</div>:null}</section>
    <section className="analytics-panel mt-6 overflow-hidden"><div className="flex items-center justify-between gap-3 p-5"><div><h2 className="font-heading text-lg font-semibold">Normalized data preview</h2><p className="text-xs text-text-secondary">Load a limited preview only when needed.</p></div><button className="action-btn" disabled={previewLoading} onClick={()=>void togglePreview()} type="button">{previewLoading?<RefreshCw className="size-4 animate-spin"/>:<FileSearch className="size-4"/>}{showPreview?"Hide preview":"Load preview"}</button></div>{showPreview?<div className="analytics-scrollbar max-h-[520px] overflow-auto border-t border-outline"><table className="min-w-[900px] text-left text-xs"><thead className="sticky top-0 bg-background"><tr>{columns.slice(0,16).map(column=><th className="whitespace-nowrap px-3 py-2.5" key={column.normalizedName}>{column.displayName}</th>)}</tr></thead><tbody>{rows.map(row=><tr className="border-t border-outline/60 hover:bg-brand-soft/30" key={row.rowNumber}>{columns.slice(0,16).map(column=><td className="max-w-48 truncate px-3 py-2.5" key={column.normalizedName}>{formatTableValue(row.data[column.normalizedName],column.dataType)}</td>)}</tr>)}</tbody></table></div>:null}</section>
  </div></main>;
}
