import { AlertTriangle, Database, ExternalLink, FileWarning, Plus, RefreshCw, Search, ShieldAlert, Trash2 } from "lucide-react";
import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { Link, useNavigate } from "react-router-dom";
import { AdminModal } from "../../components/AdminModal";
import { AdminApiError, listAnalyticsDatasets, permanentlyDeleteAnalyticsDataset, verifyAdminStepUp } from "../../services/api";
import { useAdminStore } from "../../store/admin.store";
import type { AnalyticsDataset } from "../../types/analytics";
const tones:Record<string,string>={READY:"bg-positive-soft text-success",FAILED:"bg-negative-soft text-error",ANALYZING:"bg-purple-50 text-purple-700",GENERATING:"bg-blue-50 text-secondary",PROFILING:"bg-warning-soft text-warning",PROCESSING:"bg-warning-soft text-warning",UPLOADING:"bg-gray-100 text-text-secondary"};

export function AdminAnalyticsDatasetsPage(){
  const navigate=useNavigate();const clear=useAdminStore(state=>state.clearSession);const csrf=useAdminStore(state=>state.csrfToken);const[data,setData]=useState<AnalyticsDataset[]>([]);const[query,setQuery]=useState("");const[input,setInput]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[notice,setNotice]=useState("");const[deleteTarget,setDeleteTarget]=useState<AnalyticsDataset|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await listAnalyticsDatasets({q:query,pageSize:50});setData(response.datasets)}catch(value){if(value instanceof AdminApiError&&value.status===401){clear();navigate("/login");return}setError(value instanceof Error?value.message:"Unable to load datasets")}finally{setLoading(false)}},[clear,navigate,query]);
  useEffect(()=>{void load()},[load]);function search(event:FormEvent){event.preventDefault();setQuery(input.trim())}
  const hashCounts=useMemo(()=>data.reduce<Record<string,number>>((counts,item)=>{const hash=item.file?.sha256;if(hash)counts[hash]=(counts[hash]??0)+1;return counts},{}),[data]);
  return <main className="px-4 py-7 sm:px-6 lg:px-8 lg:py-10"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm text-text-secondary">Persistent analytical sources</p><h1 className="mt-1 font-heading text-3xl font-semibold">My Datasets</h1><p className="mt-2 text-sm text-text-secondary">Upload, inspect, profile, analyze, refresh, reopen, or permanently remove datasets.</p></div><Link className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-white" to="/analytics/datasets/upload"><Plus className="size-4"/>Upload dataset</Link></div>
    <form className="mt-6 flex gap-2 rounded-2xl bg-white p-4 shadow-card" onSubmit={search}><label className="relative flex-1"><Search className="absolute left-4 top-1/2 size-5 -translate-y-1/2 text-text-secondary"/><input className="min-h-12 w-full rounded-xl border border-outline pl-12 pr-3" onChange={event=>setInput(event.target.value)} placeholder="Search datasets" value={input}/></label><button className="rounded-xl bg-primary px-5 text-sm font-semibold text-white">Search</button></form>
    {error?<p className="mt-5 flex gap-2 rounded-xl bg-negative-soft p-4 text-error"><AlertTriangle className="size-5 shrink-0"/>{error}</p>:null}{notice?<p className="mt-5 rounded-xl bg-positive-soft p-4 text-sm text-success">{notice}</p>:null}
    {loading?<div className="mt-6 grid min-h-60 place-items-center"><RefreshCw className="size-8 animate-spin text-primary"/></div>:<section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.map(dataset=>{const duplicate=Boolean(dataset.file?.sha256&&hashCounts[dataset.file.sha256]>1);return <article className="min-w-0 overflow-hidden rounded-2xl border border-outline bg-white shadow-card transition hover:border-primary/30" key={dataset.id}><Link className="block p-5" to={`/analytics/datasets/${dataset.id}`}><div className="flex items-start justify-between gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-brand-soft text-primary"><Database className="size-5"/></span><div className="flex flex-wrap justify-end gap-2">{duplicate?<span className="inline-flex items-center gap-1 rounded-full bg-warning-soft px-2.5 py-1 text-[10px] font-semibold text-warning"><FileWarning className="size-3"/>Duplicate source</span>:null}<span className={`rounded-full px-3 py-1 text-xs font-semibold ${tones[dataset.status]||"bg-gray-100"}`}>{dataset.status}</span></div></div><h2 className="mt-4 truncate font-heading text-lg font-semibold" title={dataset.name}>{dataset.name}</h2><p className="mt-2 truncate text-xs text-text-secondary" title={dataset.file?.originalFileName??undefined}>{dataset.file?.originalFileName||"No current source"}</p>{dataset.file?.sha256?<p className="mt-1 font-mono text-[10px] text-text-secondary">SHA-256 · {dataset.file.sha256.slice(0,12)}…</p>:null}<div className="mt-4 grid grid-cols-3 gap-2 border-t border-outline pt-4 text-center text-xs text-text-secondary"><span><strong className="block text-base text-text-primary">{dataset.rowCount.toLocaleString("en-IN")}</strong>Rows</span><span><strong className="block text-base text-text-primary">{dataset.columnCount}</strong>Columns</span><span><strong className="block text-base text-text-primary">{dataset.dashboardCount}</strong>Dashboards</span></div></Link><div className="flex items-center justify-between gap-2 border-t border-outline bg-[#FAFBFC] px-4 py-3"><Link className="inline-flex min-h-9 items-center gap-2 rounded-lg px-3 text-xs font-semibold text-primary hover:bg-brand-soft" to={`/analytics/datasets/${dataset.id}`}>Open dataset<ExternalLink className="size-3.5"/></Link><button className="inline-flex min-h-9 items-center gap-2 rounded-lg px-3 text-xs font-semibold text-error hover:bg-negative-soft" onClick={()=>setDeleteTarget(dataset)} type="button"><Trash2 className="size-3.5"/>Delete permanently</button></div></article>})}</section>}
    {!loading&&!data.length?<div className="mt-8 rounded-2xl bg-white p-12 text-center"><Database className="mx-auto size-10 text-text-secondary"/><h2 className="mt-4 font-heading text-xl font-semibold">No analytical datasets</h2><p className="mt-2 text-sm text-text-secondary">Upload CSV, XLSX, or XLS to begin.</p></div>:null}
    {deleteTarget&&csrf?<PermanentDeleteDialog csrfToken={csrf} dataset={deleteTarget} onClose={()=>setDeleteTarget(null)} onDeleted={()=>{setData(current=>current.filter(item=>item.id!==deleteTarget.id));setNotice(`${deleteTarget.name} and its source, normalized rows, semantic models, and dashboards were permanently deleted. The security audit tombstone was retained.`);setDeleteTarget(null)}}/>:null}
  </div></main>;
}

function PermanentDeleteDialog({dataset,csrfToken,onClose,onDeleted}:{dataset:AnalyticsDataset;csrfToken:string;onClose:()=>void;onDeleted:()=>void}){
  const[reason,setReason]=useState("");const[code,setCode]=useState("");const[confirmation,setConfirmation]=useState("");const[working,setWorking]=useState(false);const[error,setError]=useState("");
  async function submit(event:FormEvent){event.preventDefault();if(confirmation!==dataset.name){setError("Enter the complete dataset name exactly as shown.");return}setWorking(true);setError("");try{await verifyAdminStepUp(csrfToken,code);await permanentlyDeleteAnalyticsDataset(csrfToken,dataset.id,reason);onDeleted()}catch(value){setError(value instanceof Error?value.message:"Unable to permanently delete dataset")}finally{setWorking(false)}}
  return <AdminModal description="This cannot be undone. Private source files, normalized rows, profiles, semantic models, dashboard versions, filters, insights, and exports for this dataset will be removed. A minimized security audit tombstone is retained." onClose={onClose} title="Permanently delete dataset"><form className="space-y-4" onSubmit={submit}><div className="flex gap-3 rounded-xl bg-negative-soft p-4 text-sm text-error"><ShieldAlert className="size-5 shrink-0"/><p><strong>{dataset.name}</strong><br/>{dataset.rowCount.toLocaleString("en-IN")} rows · {dataset.dashboardCount} dashboard{dataset.dashboardCount===1?"":"s"}</p></div>{error?<p className="rounded-lg bg-negative-soft p-3 text-sm text-error">{error}</p>:null}<label className="block text-sm font-medium">Audit reason<textarea className="mt-2 min-h-24 w-full rounded-xl border border-outline p-3" minLength={10} onChange={event=>setReason(event.target.value)} placeholder="Why is this dataset being permanently removed?" required value={reason}/></label><label className="block text-sm font-medium">Type the complete dataset name<input className="mt-2 min-h-11 w-full rounded-xl border border-outline px-3" onChange={event=>setConfirmation(event.target.value)} required value={confirmation}/></label><label className="block text-sm font-medium">Authenticator code<input autoComplete="one-time-code" className="mt-2 min-h-11 w-full rounded-xl border border-outline px-3 font-mono tracking-widest" inputMode="numeric" maxLength={6} onChange={event=>setCode(event.target.value.replace(/\D/g,""))} required value={code}/></label><button className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-error px-4 font-semibold text-white disabled:opacity-50" disabled={working||confirmation!==dataset.name||code.length!==6||reason.trim().length<10} type="submit"><Trash2 className="size-4"/>{working?"Deleting permanently…":"Delete permanently"}</button></form></AdminModal>;
}
