import { ArrowRight, Bot, Loader2, MessageSquareText, ShieldCheck, Sparkles } from "lucide-react";
import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { askAnalyticsData } from "../../services/api";
import type { AnalyticsAskResult, DashboardQueryFilter, DashboardVisualizationSpec, SemanticModel } from "../../types/analytics";
import { ChartWidget } from "./ChartWidget";

export function AskDataPanel({dashboardId,csrfToken,filters,semantic}:{dashboardId:string;csrfToken:string;filters:DashboardQueryFilter[];semantic:SemanticModel}){
  const[question,setQuestion]=useState("");const[result,setResult]=useState<AnalyticsAskResult|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(false);const controller=useRef<AbortController|null>(null);
  useEffect(()=>()=>controller.current?.abort(),[]);
  const suggestions=useMemo(()=>{const entity=semantic.dimensions.find(item=>item.role==="ENTITY")??semantic.dimensions[0];const risk=semantic.measures.find(item=>item.role==="RISK");const geography=semantic.dimensions.find(item=>item.role==="GEOGRAPHY");const measure=semantic.measures.find(item=>item.kind==="FIELD");const date=semantic.dateFields[0];return [entity&&risk?`Which ${entity.label.toLowerCase()} have the highest ${risk.label.toLowerCase()}?`:null,geography&&measure?`Show ${measure.label.toLowerCase()} by ${geography.label.toLowerCase()}`:null,date&&measure?`How has ${measure.label.toLowerCase()} changed over time?`:null,"Summarize the current filtered portfolio"].filter((item):item is string=>Boolean(item)).slice(0,4)},[semantic]);
  async function submit(event?:FormEvent){event?.preventDefault();if(question.trim().length<3)return;controller.current?.abort();controller.current=new AbortController();setLoading(true);setError("");try{setResult(await askAnalyticsData(csrfToken,dashboardId,question.trim(),filters,controller.current.signal))}catch(value){if(!controller.current.signal.aborted)setError(value instanceof Error?value.message:"Unable to answer this question")}finally{if(!controller.current.signal.aborted)setLoading(false)}}
  const chartSpec:DashboardVisualizationSpec|undefined=result?.chart.mode==="AGGREGATE"&&result.intent.dimension?{id:"ask_result",type:result.intent.intent==="TREND"?"LINE":"BAR",title:"Answer evidence",description:null,dimension:result.intent.dimension,measure:result.intent.measure,secondaryMeasure:null,aggregation:result.intent.aggregation as DashboardVisualizationSpec["aggregation"],stackBy:null,columns:[],limit:25,timeGrain:result.intent.timeGrain,sort:result.intent.intent==="TREND"?"TIME_ASC":"VALUE_DESC",topN:result.intent.topN,showOther:false,formatOverride:"AUTO",layout:{x:0,y:0,w:12,h:4},visible:true}:undefined;
  return <section className="analytics-panel overflow-hidden" id="ask-data"><div className="grid gap-0 lg:grid-cols-[minmax(0,1fr)_minmax(360px,.8fr)]"><div className="bg-forest p-5 text-white sm:p-7"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-primary"><Sparkles className="size-5"/></span><div><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-cyan-200">Ask your data</p><h2 className="font-heading text-xl font-semibold">Natural-language analytics</h2></div></div><p className="mt-4 max-w-2xl text-sm leading-6 text-white/60">Questions are mapped to a validated query plan. PostgreSQL computes every number; AI only interprets the question and explains verified evidence.</p><form className="mt-5" onSubmit={submit}><div className="flex gap-2 rounded-xl bg-white p-2"><MessageSquareText className="ml-2 mt-2.5 size-5 shrink-0 text-text-secondary"/><input aria-label="Ask a question" className="min-h-11 min-w-0 flex-1 bg-transparent px-1 text-sm text-text-primary outline-none" onChange={event=>setQuestion(event.target.value)} placeholder="Which segments need attention?" value={question}/><button aria-label="Ask data" className="grid size-11 shrink-0 place-items-center rounded-lg bg-primary text-white disabled:opacity-50" disabled={loading||question.trim().length<3} type="submit">{loading?<Loader2 className="size-5 animate-spin"/>:<ArrowRight className="size-5"/>}</button></div></form><div className="mt-3 flex flex-wrap gap-2">{suggestions.map(item=><button className="rounded-full border border-white/15 px-3 py-1.5 text-left text-[11px] text-white/70 hover:bg-white/10" key={item} onClick={()=>setQuestion(item)} type="button">{item}</button>)}</div></div>
      <div className="min-h-[300px] p-5 sm:p-6">{error?<div className="grid h-full place-items-center text-center text-sm text-error">{error}</div>:result?<div><div className="flex items-center gap-2 text-primary"><Bot className="size-5"/><span className="text-xs font-semibold uppercase tracking-wide">Verified answer</span></div><p className="mt-3 font-heading text-lg font-semibold leading-7">{result.answer.summary}</p>{result.answer.bullets.length?<ul className="mt-3 space-y-2">{result.answer.bullets.map(item=><li className="flex gap-2 text-sm text-text-secondary" key={item}><span className="mt-2 size-1.5 shrink-0 rounded-full bg-primary"/>{item}</li>)}</ul>:null}<details className="mt-4 rounded-lg bg-background p-3"><summary className="cursor-pointer text-xs font-semibold text-primary">Methodology & evidence</summary><p className="mt-2 text-xs leading-5 text-text-secondary">{result.answer.methodology}</p><p className="mt-2 flex items-center gap-1 text-[10px] text-success"><ShieldCheck className="size-3"/>{result.answer.evidenceRefs.length} validated evidence reference(s) · {result.source.explanation}</p></details></div>:<div className="grid h-full place-items-center text-center"><div><Bot className="mx-auto size-9 text-primary"/><p className="mt-3 font-semibold">Ask a business question</p><p className="mt-1 text-xs text-text-secondary">The answer will include metrics, evidence, and methodology.</p></div></div>}</div></div>
    {result?.chart.mode==="AGGREGATE"&&chartSpec?<div className="h-80 border-t border-outline p-5"><ChartWidget result={result.chart} visualization={chartSpec}/></div>:null}
  </section>;
}
