import {
  Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart,
  ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis,
} from "recharts";
import type { AggregateQueryResult, DashboardVisualizationSpec } from "../../types/analytics";
import { formatDateLabel, formatWithMeta } from "../../utils/analytics-format";

const colors=["#0E7C86","#2563EB","#B7791F","#7C3AED","#C0152F","#0891B2","#4F46E5","#12805C","#8A93A3"];
function stacked(rows:AggregateQueryResult["rows"],isDate:boolean,timeGrain?:string|null){
  const map=new Map<string,Record<string,string|number|null>>();const keys=new Set<string>();
  for(const row of rows){const raw=row.dimension??"Unknown";const dim=isDate?formatDateLabel(raw,timeGrain):raw;const key=row.stack??"Other";keys.add(key);const item=map.get(dim)??{name:dim,rawName:raw};item[key]=row.value;map.set(dim,item);}
  return{data:[...map.values()],keys:[...keys]};
}
function tooltipFormatter(value:unknown,result:AggregateQueryResult,override:DashboardVisualizationSpec["formatOverride"]){
  const number=typeof value==="number"?value:Number(value);return formatWithMeta(Number.isFinite(number)?number:null,result.format,override??"AUTO",false);
}

export function ChartWidget({visualization,result,onSelect}:{visualization:DashboardVisualizationSpec;result:AggregateQueryResult;onSelect?:(field:string,value:string)=>void}){
  const type=visualization.type;const isDate=Boolean(result.timeGrain);const data=result.rows.map(row=>({name:isDate&&row.dimension?formatDateLabel(row.dimension,result.timeGrain):row.dimension??"Total",rawName:row.dimension??"Total",value:row.value??0,secondary:row.secondaryValue??0,stack:row.stack??null}));
  const choose=(entry:unknown)=>{if(!visualization.dimension||!entry||typeof entry!=="object")return;const value=(entry as {rawName?:unknown;name?:unknown}).rawName??(entry as {name?:unknown}).name;if(typeof value==="string"&&value!=="Other")onSelect?.(visualization.dimension,value)};
  const tooltipProps={formatter:(value:unknown)=>tooltipFormatter(value,result,visualization.formatOverride),labelFormatter:(label:unknown)=>String(label)};
  const valueTick=(value:unknown)=>tooltipFormatter(value,result,visualization.formatOverride);
  if(!data.length)return <div className="grid h-full place-items-center text-center"><div><p className="font-semibold">No matching data</p><p className="mt-1 text-xs text-text-secondary">Adjust or clear filters to populate this chart.</p></div></div>;
  if(type==="PIE"||type==="DONUT")return <ResponsiveContainer height="100%" width="100%"><PieChart><Pie data={data} dataKey="value" innerRadius={type==="DONUT"?54:0} nameKey="name" onClick={choose} outerRadius={84} paddingAngle={2}>{data.map((entry,index)=><Cell className="cursor-pointer outline-none" fill={colors[index%colors.length]} key={`${entry.rawName}-${index}`}/>)}</Pie><Tooltip {...tooltipProps}/><Legend iconSize={9} wrapperStyle={{fontSize:11}}/></PieChart></ResponsiveContainer>;
  if(type==="SCATTER")return <ResponsiveContainer height="100%" width="100%"><ScatterChart margin={{left:4,right:16,top:8,bottom:4}}><CartesianGrid stroke="#E2E6ED" strokeDasharray="3 3"/><XAxis dataKey="value" tickFormatter={valueTick} tick={{fontSize:10,fill:"#5B6472"}} type="number"/><YAxis dataKey="secondary" tick={{fontSize:10,fill:"#5B6472"}} type="number"/><Tooltip {...tooltipProps}/><Scatter data={data} fill={colors[0]} onClick={choose}/></ScatterChart></ResponsiveContainer>;
  if(type==="STACKED_BAR"||type==="STACKED_AREA"){
    const grouped=stacked(result.rows,isDate,result.timeGrain);
    return <ResponsiveContainer height="100%" width="100%">{type==="STACKED_BAR"?<BarChart data={grouped.data} margin={{left:0,right:8,top:8,bottom:4}}><CartesianGrid stroke="#E2E6ED" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" interval="preserveStartEnd" tick={{fontSize:10,fill:"#5B6472"}}/><YAxis tickFormatter={valueTick} tick={{fontSize:10,fill:"#5B6472"}} width={56}/><Tooltip {...tooltipProps}/><Legend iconSize={9} wrapperStyle={{fontSize:10}}/>{grouped.keys.map((key,index)=><Bar cursor="pointer" dataKey={key} fill={colors[index%colors.length]} key={key} onClick={choose} stackId="a"/>)}</BarChart>:<AreaChart data={grouped.data} margin={{left:0,right:8,top:8,bottom:4}}><CartesianGrid stroke="#E2E6ED" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" interval="preserveStartEnd" tick={{fontSize:10,fill:"#5B6472"}}/><YAxis tickFormatter={valueTick} tick={{fontSize:10,fill:"#5B6472"}} width={56}/><Tooltip {...tooltipProps}/><Legend iconSize={9} wrapperStyle={{fontSize:10}}/>{grouped.keys.map((key,index)=><Area dataKey={key} fill={colors[index%colors.length]} fillOpacity={0.55} key={key} stackId="a" stroke={colors[index%colors.length]}/>)}</AreaChart>}</ResponsiveContainer>;
  }
  if(type==="LINE")return <ResponsiveContainer height="100%" width="100%"><LineChart data={data} margin={{left:0,right:12,top:8,bottom:4}}><CartesianGrid stroke="#E2E6ED" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" interval="preserveStartEnd" tick={{fontSize:10,fill:"#5B6472"}}/><YAxis tickFormatter={valueTick} tick={{fontSize:10,fill:"#5B6472"}} width={56}/><Tooltip {...tooltipProps}/><Line dataKey="value" dot={data.length<20} stroke={colors[0]} strokeWidth={2.5}/></LineChart></ResponsiveContainer>;
  if(type==="AREA")return <ResponsiveContainer height="100%" width="100%"><AreaChart data={data} margin={{left:0,right:12,top:8,bottom:4}}><defs><linearGradient id={`area-${visualization.id}`} x1="0" x2="0" y1="0" y2="1"><stop offset="5%" stopColor={colors[0]} stopOpacity={0.35}/><stop offset="95%" stopColor={colors[0]} stopOpacity={0.03}/></linearGradient></defs><CartesianGrid stroke="#E2E6ED" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" interval="preserveStartEnd" tick={{fontSize:10,fill:"#5B6472"}}/><YAxis tickFormatter={valueTick} tick={{fontSize:10,fill:"#5B6472"}} width={56}/><Tooltip {...tooltipProps}/><Area dataKey="value" fill={`url(#area-${visualization.id})`} stroke={colors[0]} strokeWidth={2}/></AreaChart></ResponsiveContainer>;
  const horizontal=data.length>8;
  return <ResponsiveContainer height="100%" width="100%"><BarChart data={data} layout={horizontal?"vertical":"horizontal"} margin={horizontal?{left:8,right:22,top:4,bottom:4}:{left:0,right:8,top:8,bottom:4}}>{horizontal?<><CartesianGrid horizontal={false} stroke="#E2E6ED" strokeDasharray="3 3"/><XAxis tickFormatter={valueTick} tick={{fontSize:10,fill:"#5B6472"}} type="number"/><YAxis dataKey="name" tick={{fontSize:10,fill:"#5B6472"}} type="category" width={110}/></>:<><CartesianGrid stroke="#E2E6ED" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" interval={data.length>12?1:0} tick={{fontSize:10,fill:"#5B6472"}}/><YAxis tickFormatter={valueTick} tick={{fontSize:10,fill:"#5B6472"}} width={56}/></>}<Tooltip {...tooltipProps}/><Bar cursor="pointer" dataKey="value" fill={colors[0]} onClick={choose} radius={horizontal?[0,5,5,0]:[5,5,0,0]}/></BarChart></ResponsiveContainer>;
}
