import { AlertTriangle, CheckCircle2 } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { useNavigate } from "react-router-dom";
import {
  deleteAnalyticsDashboard, downloadAnalyticsExport, duplicateAnalyticsDashboard, getAnalyticsDashboard,
  getAnalyticsDatasetStatus, getAnalyticsEvidenceInsights, getAnalyticsFilterOptions, regenerateAnalyticsDashboard,
  saveAnalyticsDashboard, verifyAdminStepUp,
} from "../../services/api";
import { useAnalyticsDashboardStore } from "../../store/analytics.store";
import type { AnalyticsDashboardDetail, DashboardFilterSpec, DashboardQueryFilter, DashboardSpecification, DashboardVisualizationSpec } from "../../types/analytics";
import { AdminModal } from "../AdminModal";
import { AskDataPanel } from "./AskDataPanel";
import { ComparisonStudio } from "./ComparisonStudio";
import { DashboardFilters } from "./DashboardFilters";
import { DashboardGrid } from "./DashboardGrid";
import { DashboardHeader } from "./DashboardHeader";
import { DatasetInfo } from "./DatasetInfo";
import { InsightPanel } from "./InsightPanel";
import { VisualizationEditor } from "./VisualizationEditor";

function normalizedVisualizations(items:DashboardVisualizationSpec[]):DashboardVisualizationSpec[]{return items.map(item=>({...item,timeGrain:item.timeGrain??"AUTO" as const,sort:item.sort??(item.type==="LINE"?"TIME_ASC":"VALUE_DESC"),topN:item.topN??10,showOther:item.showOther??true,formatOverride:item.formatOverride??"AUTO" as const}))}
function useDebouncedFilters(filters:DashboardQueryFilter[],delay=250){const[value,setValue]=useState(filters);useEffect(()=>{const timer=window.setTimeout(()=>setValue(filters),delay);return()=>window.clearTimeout(timer)},[filters,delay]);return value}
function safeFilterId(field:string){return `cross_${field.toLowerCase().replace(/[^a-z0-9_]+/g,"_").replace(/^_+/,"")}`.slice(0,100)}
function triggerDownload(blob:Blob,fileName:string){const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=fileName;document.body.append(link);link.click();link.remove();URL.revokeObjectURL(url)}

export function DashboardShell({initial,csrfToken,initialEdit=false}:{initial:AnalyticsDashboardDetail;csrfToken:string;initialEdit?:boolean}){
  const navigate=useNavigate();const setDashboard=useAnalyticsDashboardStore(state=>state.setDashboard);const filterMap=useAnalyticsDashboardStore(state=>state.filters);const setFilter=useAnalyticsDashboardStore(state=>state.setFilter);const reset=useAnalyticsDashboardStore(state=>state.reset);
  const[detail,setDetail]=useState(initial);const[spec,setSpec]=useState<DashboardSpecification>(()=>({...initial.specification,visualizations:normalizedVisualizations(initial.specification.visualizations)}));const[editing,setEditing]=useState(initialEdit);const[selected,setSelected]=useState<DashboardVisualizationSpec|null>(null);const[comparisonRequest,setComparisonRequest]=useState(0);const[options,setOptions]=useState<Record<string,string[]>>({});const[error,setError]=useState("");const[notice,setNotice]=useState("");const[saving,setSaving]=useState(false);const[regenerating,setRegenerating]=useState(false);const[deleting,setDeleting]=useState(false);const[refreshNonce,setRefreshNonce]=useState(0);const[runtimeInsights,setRuntimeInsights]=useState<Array<{id:string;title:string;content:string;confidence:number;evidence:unknown[]}>>([]);const[insightsLoading,setInsightsLoading]=useState(false);const optionController=useRef<AbortController|null>(null);
  useEffect(()=>{setDashboard(initial.id);for(const saved of initial.currentVersion.filterState??[]){const definition=initial.specification.filters.find(item=>item.field===saved.field);if(definition)setFilter(definition.id,saved)}return()=>reset()},[initial,reset,setDashboard,setFilter]);
  const filters=useMemo(()=>Object.values(filterMap),[filterMap]);const debouncedFilters=useDebouncedFilters(filters);
  const loadOptions=useCallback(async(filter:DashboardFilterSpec,search="")=>{try{const response=await getAnalyticsFilterOptions(csrfToken,detail.id,{field:filter.field,search,limit:100,filters:debouncedFilters.filter(item=>item.field!==filter.field)},optionController.current?.signal);setOptions(current=>({...current,[filter.id]:response.options.map(item=>item.value)}))}catch(error){if(!(error instanceof DOMException&&error.name==="AbortError")){/* Searchable controls remain usable with already loaded options. */}}},[csrfToken,debouncedFilters,detail.id]);
  useEffect(()=>{optionController.current?.abort();optionController.current=new AbortController();const searchable=spec.filters.filter(item=>["SELECT","MULTI_SELECT"].includes(item.type));void Promise.all(searchable.map(item=>loadOptions(item)));return()=>optionController.current?.abort()},[loadOptions,spec.filters]);
  async function persistSpecification(nextSpec:DashboardSpecification,changeSummary:string){setSaving(true);setError("");try{const response=await saveAnalyticsDashboard(csrfToken,detail.id,detail.currentVersion.version,nextSpec,filters,changeSummary);const fresh=await getAnalyticsDashboard(detail.id);setDetail(fresh.dashboard);setSpec({...fresh.dashboard.specification,visualizations:normalizedVisualizations(fresh.dashboard.specification.visualizations)});setRefreshNonce(value=>value+1);return response}catch(value){setError(value instanceof Error?value.message:"Unable to save dashboard");throw value}finally{setSaving(false)}}
  async function save(){try{const response=await persistSpecification(spec,"Visualization, formatting, and filter configuration updated");setEditing(false);setNotice(`Dashboard version ${response.version} saved with canonical specification integrity.`)}catch{/* Error is displayed by persistSpecification. */}}
  async function addComparison(item:DashboardVisualizationSpec){const next={...spec,visualizations:[...spec.visualizations,item]};const response=await persistSpecification(next,`Added custom comparison chart: ${item.title}`);setNotice(`Comparison chart added and saved as dashboard version ${response.version}.`)}
  async function removeComparison(id:string){const item=spec.visualizations.find(value=>value.id===id);if(!item)return;const next={...spec,visualizations:spec.visualizations.filter(value=>value.id!==id)};try{const response=await persistSpecification(next,`Removed custom comparison chart: ${item.title}`);setNotice(`Comparison chart removed in dashboard version ${response.version}.`)}catch{/* Error is displayed by persistSpecification. */}}
  async function regenerate(){setRegenerating(true);setError("");try{await regenerateAnalyticsDashboard(csrfToken,detail.id);for(let attempt=0;attempt<120;attempt+=1){const status=await getAnalyticsDatasetStatus(detail.datasetId);if(status.status==="READY")break;if(status.status==="FAILED")throw new Error(status.failure?.message||"Dashboard regeneration failed");await new Promise(resolve=>window.setTimeout(resolve,300))}const fresh=await getAnalyticsDashboard(detail.id);setDetail(fresh.dashboard);setSpec({...fresh.dashboard.specification,visualizations:normalizedVisualizations(fresh.dashboard.specification.visualizations)});setNotice(`Regenerated as version ${fresh.dashboard.currentVersion.version}; semantic reconciliation and query preflight passed.`);setRefreshNonce(value=>value+1)}catch(value){setError(value instanceof Error?value.message:"Regeneration failed")}finally{setRegenerating(false)}}
  async function duplicate(){try{const response=await duplicateAnalyticsDashboard(csrfToken,detail.id);navigate(`/analytics/dashboards/${response.dashboardId}`)}catch(value){setError(value instanceof Error?value.message:"Unable to duplicate dashboard")}}
  function apply(item:DashboardVisualizationSpec){setSpec(current=>({...current,visualizations:current.visualizations.map(value=>value.id===item.id?item:value)}));setSelected(null)}
  const exportRows=useCallback(async(fields:string[])=>{setError("");try{const response=await downloadAnalyticsExport(csrfToken,detail.id,{fields,filters,limit:50_000});triggerDownload(response.blob,response.fileName);setNotice("CSV export created from the current deterministic filter state.")}catch(value){setError(value instanceof Error?value.message:"Unable to export dashboard data")}},[csrfToken,detail.id,filters]);
  async function refreshInsights(){setInsightsLoading(true);try{const response=await getAnalyticsEvidenceInsights(csrfToken,detail.id,debouncedFilters);setRuntimeInsights(response.insights)}catch(value){setError(value instanceof Error?value.message:"Unable to compute evidence insights")}finally{setInsightsLoading(false)}}
  function crossFilter(field:string,value:string){let definition=spec.filters.find(item=>item.field===field);if(!definition){definition={id:safeFilterId(field),field,label:detail.columns.find(column=>column.normalizedName===field)?.displayName??field,type:"SELECT"};setSpec(current=>({...current,filters:[...current.filters,definition!].slice(0,12)}))}setFilter(definition.id,definition.type==="MULTI_SELECT"?{field,type:"MULTI_SELECT",values:[value]}:{field,type:"SELECT",value});setNotice(`Cross-filter applied: ${definition.label} = ${value}`)}
  const exportFields=spec.visualizations.find(item=>item.type==="TABLE")?.columns??detail.columns.map(column=>column.normalizedName).slice(0,30);
  return <div className="space-y-5 sm:space-y-6">
    <DashboardHeader dataset={detail.dataset.name} description={spec.description} editable={editing} onAddComparison={()=>setComparisonRequest(value=>value+1)} onAsk={()=>document.getElementById("ask-data")?.scrollIntoView({behavior:"smooth",block:"start"})} onDelete={()=>setDeleting(true)} onDuplicate={()=>void duplicate()} onExport={()=>void exportRows(exportFields)} onPresent={()=>window.open(`/analytics/dashboards/${detail.id}/present`,"_blank","noopener,noreferrer")} onRefresh={()=>setRefreshNonce(value=>value+1)} onRegenerate={()=>void regenerate()} onSave={()=>void save()} onToggleEdit={()=>setEditing(true)} regenerating={regenerating} saving={saving} title={spec.title} updatedAt={detail.updatedAt}/>
    {error?<div className="flex gap-3 rounded-xl bg-negative-soft p-4 text-sm text-error"><AlertTriangle className="size-5 shrink-0"/>{error}</div>:null}
    {notice?<div className="flex gap-3 rounded-xl bg-positive-soft p-4 text-sm text-success"><CheckCircle2 className="size-5 shrink-0"/>{notice}</div>:null}
    <DatasetInfo columns={detail.dataset.columnCount} domain={detail.semanticModel.businessDomain} name={detail.dataset.name} rows={detail.dataset.rowCount} version={detail.dataset.datasetVersion}/>
    <DashboardFilters filters={spec.filters} onChange={setFilter} onClear={()=>spec.filters.forEach(filter=>setFilter(filter.id,null))} onSearchOptions={(filter,search)=>void loadOptions(filter,search)} options={options} values={filterMap}/>
    <div id="comparison-studio"><ComparisonStudio columns={detail.columns} onAdd={addComparison} onRemove={removeComparison} openRequest={comparisonRequest} saving={saving} semantic={detail.semanticModel} visualizations={spec.visualizations}/></div>
    <DashboardGrid columns={detail.columns} csrfToken={csrfToken} dashboardId={detail.id} editable={editing} filters={debouncedFilters} onCrossFilter={crossFilter} onEdit={setSelected} onExport={fields=>void exportRows(fields)} refreshNonce={refreshNonce} visualizations={spec.visualizations}/>
    <InsightPanel insights={spec.insights} loading={insightsLoading} onRefresh={()=>void refreshInsights()} runtime={runtimeInsights}/>
    <AskDataPanel csrfToken={csrfToken} dashboardId={detail.id} filters={debouncedFilters} semantic={detail.semanticModel}/>
    {selected?<VisualizationEditor columns={detail.columns} item={selected} onApply={apply} onClose={()=>setSelected(null)} semantic={detail.semanticModel}/>:null}
    {deleting?<DeleteDialog csrfToken={csrfToken} dashboardId={detail.id} onClose={()=>setDeleting(false)} onDeleted={()=>navigate("/analytics/dashboards")}/>:null}
  </div>;
}
function DeleteDialog({csrfToken,dashboardId,onClose,onDeleted}:{csrfToken:string;dashboardId:string;onClose:()=>void;onDeleted:()=>void}){const[reason,setReason]=useState("");const[code,setCode]=useState("");const[working,setWorking]=useState(false);const[error,setError]=useState("");async function submit(event:FormEvent){event.preventDefault();setWorking(true);setError("");try{await verifyAdminStepUp(csrfToken,code);await deleteAnalyticsDashboard(csrfToken,dashboardId,reason);onDeleted()}catch(value){setError(value instanceof Error?value.message:"Delete failed")}finally{setWorking(false)}}return <AdminModal onClose={onClose} title="Delete dashboard"><form className="space-y-4" onSubmit={submit}>{error?<p className="rounded-lg bg-negative-soft p-3 text-sm text-error">{error}</p>:null}<label className="block text-sm font-medium">Audit reason<textarea className="mt-2 min-h-24 w-full rounded-xl border border-outline p-3" minLength={10} onChange={event=>setReason(event.target.value)} required value={reason}/></label><label className="block text-sm font-medium">Authenticator code<input className="mt-2 min-h-11 w-full rounded-xl border border-outline px-3" maxLength={6} onChange={event=>setCode(event.target.value.replace(/\D/g,""))} required value={code}/></label><button className="min-h-12 w-full rounded-xl bg-error font-semibold text-white" disabled={working}>Delete dashboard</button></form></AdminModal>}
