import { AlertTriangle, Edit3, Maximize2, RefreshCw } from "lucide-react";
import type { AnalyticsColumn, DashboardQueryResult, DashboardVisualizationSpec, TimeGrain } from "../../types/analytics";
import { VisualizationRenderer } from "./VisualizationRenderer";

const widthClasses:Record<number,string>={1:"lg:col-span-1",2:"lg:col-span-2",3:"sm:col-span-1 lg:col-span-3",4:"sm:col-span-1 lg:col-span-4",5:"sm:col-span-2 lg:col-span-5",6:"sm:col-span-2 lg:col-span-6",7:"sm:col-span-2 lg:col-span-7",8:"sm:col-span-2 lg:col-span-8",9:"sm:col-span-2 lg:col-span-9",10:"sm:col-span-2 lg:col-span-10",11:"sm:col-span-2 lg:col-span-11",12:"sm:col-span-2 lg:col-span-12"};
interface Props {visualization:DashboardVisualizationSpec;result?:DashboardQueryResult;error?:string;loading:boolean;columns:AnalyticsColumn[];editable:boolean;onEdit:()=>void;onRefresh:()=>void;onPageChange:(page:number)=>void;onCrossFilter:(field:string,value:string)=>void;onExport:()=>void;onExpand:()=>void;onOptions:(input:{topN?:number;timeGrain?:TimeGrain})=>void;}
export function DashboardWidget({visualization,result,error,loading,columns,editable,onEdit,onRefresh,onPageChange,onCrossFilter,onExport,onExpand,onOptions}:Props){
  const width=Math.min(12,Math.max(1,visualization.layout.w));const table=visualization.type==="TABLE";const kpi=visualization.type==="KPI";const time=Boolean(visualization.timeGrain&&visualization.timeGrain!=="AUTO")||["LINE","AREA","STACKED_AREA"].includes(visualization.type);
  if(kpi)return <article className={`analytics-widget-reveal relative col-span-1 min-w-0 rounded-[10px] border border-outline bg-white p-3 shadow-card ${widthClasses[width]??"lg:col-span-3"} min-h-[196px]`}>
    <div className="absolute right-5 top-5 z-10 flex items-center gap-1 text-white/70">{editable?<button aria-label={`Edit ${visualization.title}`} className="grid size-8 place-items-center rounded-lg bg-white/10 hover:bg-white/20" onClick={onEdit} type="button"><Edit3 className="size-3.5"/></button>:null}<button aria-label={`Refresh ${visualization.title}`} className="grid size-8 place-items-center rounded-lg bg-white/10 hover:bg-white/20" onClick={onRefresh} type="button"><RefreshCw className={`size-3.5 ${loading?"animate-spin":""}`}/></button></div>
    <div className="h-[170px]">{loading&&!result?<div className="h-full animate-pulse rounded-xl bg-forest/90"/>:error&&!result?<div className="grid h-full place-items-center rounded-xl bg-negative-soft p-4 text-center text-sm text-error"><div><AlertTriangle className="mx-auto size-6"/><p className="mt-2">{error}</p><button className="mt-3 text-xs font-semibold underline" onClick={onRefresh} type="button">Try again</button></div></div>:result?<VisualizationRenderer columns={columns} result={result} visualization={visualization}/>:null}</div>
    {loading&&result?<div className="pointer-events-none absolute inset-x-3 top-3 h-0.5 overflow-hidden rounded-full bg-brand-soft"><div className="h-full w-1/2 animate-pulse bg-primary"/></div>:null}
  </article>;
  return <article className={`analytics-widget-reveal col-span-1 min-w-0 rounded-[10px] border border-outline bg-white shadow-card ${widthClasses[width]??"lg:col-span-6"} ${table?"min-h-[520px]":"min-h-[360px]"}`}>
    <div className="flex min-h-[68px] flex-wrap items-start justify-between gap-2 border-b border-outline/80 px-4 py-3 sm:px-5"><div className="min-w-0 flex-1"><h3 className="truncate font-heading text-sm font-semibold" title={visualization.title}>{visualization.title}</h3>{visualization.description?<p className="mt-1 line-clamp-1 text-[11px] text-text-secondary">{visualization.description}</p>:null}</div><div className="flex items-center gap-1">
      {!kpi&&!table&&!time?<select aria-label={`Top N for ${visualization.title}`} className="min-h-8 rounded-lg border border-outline bg-white px-1 text-[11px]" onChange={event=>onOptions({topN:Number(event.target.value)})} value={visualization.topN??10}>{[5,10,20,50].map(value=><option key={value} value={value}>Top {value}</option>)}</select>:null}
      {!kpi&&!table&&time?<select aria-label={`Time grain for ${visualization.title}`} className="min-h-8 rounded-lg border border-outline bg-white px-1 text-[11px]" onChange={event=>onOptions({timeGrain:event.target.value as TimeGrain})} value={visualization.timeGrain??"MONTH"}>{["DAY","WEEK","MONTH","QUARTER","YEAR"].map(value=><option key={value}>{value}</option>)}</select>:null}
      {editable?<button aria-label={`Edit ${visualization.title}`} className="grid size-8 place-items-center rounded-lg hover:bg-background" onClick={onEdit} type="button"><Edit3 className="size-3.5"/></button>:null}
      <button aria-label={`Refresh ${visualization.title}`} className="grid size-8 place-items-center rounded-lg hover:bg-background" onClick={onRefresh} type="button"><RefreshCw className={`size-3.5 ${loading?"animate-spin":""}`}/></button>
      <button aria-label={`Expand ${visualization.title}`} className="grid size-8 place-items-center rounded-lg hover:bg-background" onClick={onExpand} title="Expand chart" type="button"><Maximize2 className="size-3.5"/></button>
    </div></div>
    <div className={`relative ${kpi?"h-[112px] p-3":table?"h-[450px]":"h-[292px] p-4 pt-3"}`}>
      {loading&&!result?<div className="h-full animate-pulse rounded-xl bg-background"/>:error&&!result?<div className="grid h-full place-items-center text-center text-sm text-error"><div><AlertTriangle className="mx-auto size-6"/><p className="mt-2 max-w-xs">{error}</p><button className="mt-3 text-xs font-semibold underline" onClick={onRefresh} type="button">Try again</button></div></div>:result?<VisualizationRenderer columns={columns} onCrossFilter={onCrossFilter} onExport={onExport} onPageChange={onPageChange} result={result} visualization={visualization}/>:null}
      {loading&&result?<div className="pointer-events-none absolute inset-x-0 top-0 h-0.5 overflow-hidden bg-brand-soft"><div className="h-full w-1/2 animate-pulse bg-primary"/></div>:null}
    </div>
  </article>;
}
