import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { queryAnalyticsVisualization, queryAnalyticsVisualizationsBatch } from "../../services/api";
import type { AnalyticsColumn, DashboardQueryFilter, DashboardQueryResult, DashboardVisualizationSpec, TimeGrain } from "../../types/analytics";
import { DashboardWidget } from "./DashboardWidget";
import { ExpandedVisualizationDialog } from "./ExpandedVisualizationDialog";

interface Props {dashboardId:string;visualizations:DashboardVisualizationSpec[];filters:DashboardQueryFilter[];columns:AnalyticsColumn[];csrfToken:string;editable:boolean;onEdit:(item:DashboardVisualizationSpec)=>void;refreshNonce:number;onCrossFilter:(field:string,value:string)=>void;onExport:(fields:string[])=>void;}
export function DashboardGrid({dashboardId,visualizations,filters,columns,csrfToken,editable,onEdit,refreshNonce,onCrossFilter,onExport}:Props){
  const[results,setResults]=useState<Record<string,DashboardQueryResult>>({});const[errors,setErrors]=useState<Record<string,string>>({});const[loading,setLoading]=useState<Record<string,boolean>>({});const[overrides,setOverrides]=useState<Record<string,{topN?:number;timeGrain?:TimeGrain}>>({});const[expandedId,setExpandedId]=useState<string|null>(null);
  const batchSequence=useRef(0);const requestSequences=useRef(new Map<string,number>());const controllers=useRef(new Map<string,AbortController>());
  const visible=useMemo(()=>visualizations.filter(item=>item.visible).sort((left,right)=>left.layout.y-right.layout.y||left.layout.x-right.layout.x),[visualizations]);
  useEffect(()=>{const controller=new AbortController();const sequence=++batchSequence.current;setLoading(Object.fromEntries(visible.map(item=>[item.id,true])));void queryAnalyticsVisualizationsBatch(csrfToken,dashboardId,filters,visible.map(item=>item.id),controller.signal).then(response=>{if(sequence!==batchSequence.current)return;const nextResults:Record<string,DashboardQueryResult>={};const nextErrors:Record<string,string>={};for(const[itemId,entry]of Object.entries(response.widgets)){if(entry.result)nextResults[itemId]=entry.result;if(entry.error)nextErrors[itemId]=entry.error;}setResults(nextResults);setErrors(nextErrors)}).catch(error=>{if(controller.signal.aborted)return;setErrors(Object.fromEntries(visible.map(item=>[item.id,error instanceof Error?error.message:"Unable to query dashboard"])))}).finally(()=>{if(sequence===batchSequence.current)setLoading({})});return()=>controller.abort()},[csrfToken,dashboardId,filters,refreshNonce,visible]);
  useEffect(()=>()=>{for(const controller of controllers.current.values())controller.abort()},[]);
  const queryOne=useCallback(async(item:DashboardVisualizationSpec,input:Record<string,unknown>={})=>{controllers.current.get(item.id)?.abort();const controller=new AbortController();controllers.current.set(item.id,controller);const sequence=(requestSequences.current.get(item.id)??0)+1;requestSequences.current.set(item.id,sequence);setLoading(current=>({...current,[item.id]:true}));setErrors(current=>{const next={...current};delete next[item.id];return next});try{const result=await queryAnalyticsVisualization(csrfToken,dashboardId,item.id,{filters,...overrides[item.id],...input},controller.signal);if(requestSequences.current.get(item.id)===sequence)setResults(current=>({...current,[item.id]:result}))}catch(error){if(!controller.signal.aborted&&requestSequences.current.get(item.id)===sequence)setErrors(current=>({...current,[item.id]:error instanceof Error?error.message:"Unable to query visualization"}))}finally{if(requestSequences.current.get(item.id)===sequence)setLoading(current=>({...current,[item.id]:false}))}},[csrfToken,dashboardId,filters,overrides]);
  const expandedBase=visible.find(item=>item.id===expandedId);const expanded=expandedBase?{...expandedBase,...overrides[expandedBase.id]}:null;
  const fieldsFor=(item:DashboardVisualizationSpec)=>item.columns.length?item.columns:columns.map(column=>column.normalizedName);
  return <><section className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-12 lg:gap-5">{visible.map(item=>{const display={...item,...overrides[item.id]};return <DashboardWidget columns={columns} editable={editable} error={errors[item.id]} key={item.id} loading={Boolean(loading[item.id])} onCrossFilter={onCrossFilter} onEdit={()=>onEdit(item)} onExpand={()=>setExpandedId(item.id)} onExport={()=>onExport(fieldsFor(item))} onOptions={options=>{setOverrides(current=>({...current,[item.id]:{...current[item.id],...options}}));void queryOne(item,options)}} onPageChange={page=>void queryOne(item,{page})} onRefresh={()=>void queryOne(item)} result={results[item.id]} visualization={display}/>})}</section>{expanded&&expandedBase?<ExpandedVisualizationDialog columns={columns} error={errors[expanded.id]} loading={Boolean(loading[expanded.id])} onClose={()=>setExpandedId(null)} onCrossFilter={onCrossFilter} onExport={()=>onExport(fieldsFor(expandedBase))} onPageChange={page=>void queryOne(expandedBase,{page})} onRefresh={()=>void queryOne(expandedBase)} result={results[expanded.id]} visualization={expanded}/>:null}</>;
}
