import { BrainCircuit, ChevronDown, ChevronUp, ShieldCheck, Sparkles } from "lucide-react";
import { useState } from "react";
import type { DashboardInsightSpec } from "../../types/analytics";
interface RuntimeInsight {id:string;title:string;content:string;confidence:number;evidence:unknown[];}
export function InsightPanel({insights,runtime=[],loading=false,onRefresh}:{insights:DashboardInsightSpec[];runtime?:RuntimeInsight[];loading?:boolean;onRefresh?:()=>void}){
  const[open,setOpen]=useState<string|null>(null);const all=[...runtime,...insights];if(!all.length&&!loading)return null;
  return <section className="analytics-panel overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-outline bg-[#F8F9FB] px-5 py-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-brand-soft text-primary"><BrainCircuit className="size-5"/></span><div><p className="analytics-kicker">Deterministic + AI narrative</p><h2 className="font-heading text-lg font-semibold">Analytical insights</h2></div></div>{onRefresh?<button className="inline-flex min-h-9 items-center gap-2 rounded-lg border border-outline bg-white px-3 text-xs font-semibold" disabled={loading} onClick={onRefresh} type="button"><Sparkles className={`size-3.5 ${loading?"animate-pulse":""}`}/>{loading?"Computing…":"Refresh evidence"}</button>:null}</div>
    <div className="grid gap-3 p-4 lg:grid-cols-2 lg:p-5">{all.map(insight=>{const expanded=open===insight.id;return <article className="rounded-xl border border-outline bg-white p-4" key={insight.id}><div className="flex items-start justify-between gap-3"><h3 className="font-semibold">{insight.title}</h3>{insight.confidence!==null?<span className="rounded-full bg-positive-soft px-2 py-1 text-[10px] font-semibold text-success">{Math.round(insight.confidence*100)}% confidence</span>:null}</div><p className="mt-2 text-sm leading-6 text-text-secondary">{insight.content}</p><button className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-primary" onClick={()=>setOpen(expanded?null:insight.id)} type="button"><ShieldCheck className="size-3.5"/>View evidence {expanded?<ChevronUp className="size-3"/>:<ChevronDown className="size-3"/>}</button>{expanded?<pre className="analytics-scrollbar mt-3 max-h-48 overflow-auto rounded-lg bg-background p-3 text-[10px] leading-5 text-text-secondary">{JSON.stringify(insight.evidence,null,2)}</pre>:null}</article>})}</div>
  </section>;
}
