import { ChevronLeft, ChevronRight, Columns3, Download, Eye, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { TableQueryResult } from "../../types/analytics";
import { formatTableValue } from "../../utils/analytics-format";

interface Props {result:TableQueryResult;labels:Record<string,string>;onPageChange?:(page:number)=>void;onFieldsChange?:(fields:string[])=>void;onExport?:()=>void;}
export function TableWidget({result,labels,onPageChange,onFieldsChange,onExport}:Props){
  const[visible,setVisible]=useState(result.fields);const[chooser,setChooser]=useState(false);const[selected,setSelected]=useState<TableQueryResult["rows"][number]|null>(null);
  useEffect(()=>setVisible(current=>{const kept=current.filter(field=>result.fields.includes(field));return kept.length?kept:result.fields}),[result.fields]);
  const shown=useMemo(()=>result.fields.filter(field=>visible.includes(field)),[result.fields,visible]);
  const toggle=(field:string)=>{const next=visible.includes(field)?visible.filter(item=>item!==field):[...visible,field];if(!next.length)return;setVisible(next);onFieldsChange?.(result.fields.filter(item=>next.includes(item)))};
  return <div className="flex h-full min-h-0 flex-col">
    <div className="flex flex-wrap items-center justify-between gap-2 border-b border-outline px-3 py-2">
      <p className="text-xs text-text-secondary"><strong className="text-text-primary">{result.pagination.total.toLocaleString("en-IN")}</strong> matching rows</p>
      <div className="relative flex gap-1"><button className="inline-flex min-h-8 items-center gap-1 rounded-lg px-2 text-xs font-semibold hover:bg-background" onClick={()=>setChooser(!chooser)} type="button"><Columns3 className="size-3.5"/>Columns</button>{onExport?<button className="inline-flex min-h-8 items-center gap-1 rounded-lg px-2 text-xs font-semibold hover:bg-background" onClick={onExport} type="button"><Download className="size-3.5"/>CSV</button>:null}{chooser?<div className="absolute right-0 top-9 z-30 w-64 rounded-xl border border-outline bg-white p-2 shadow-analytics"><p className="px-2 py-1 text-xs font-semibold">Visible columns</p><div className="analytics-scrollbar max-h-56 overflow-y-auto">{result.fields.map(field=><label className="flex min-h-9 items-center gap-2 rounded-lg px-2 text-xs hover:bg-background" key={field}><input checked={visible.includes(field)} className="accent-primary" onChange={()=>toggle(field)} type="checkbox"/>{labels[field]??field}</label>)}</div></div>:null}</div>
    </div>
    <div className="analytics-scrollbar min-h-0 flex-1 overflow-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="sticky top-0 z-10 bg-[#F8F9FB] text-text-secondary"><tr>{shown.map(field=><th className="whitespace-nowrap px-3 py-2.5 font-semibold" key={field}>{labels[field]??field}</th>)}<th className="w-12 px-2"><span className="sr-only">Details</span></th></tr></thead><tbody className="divide-y divide-outline/70">{result.rows.map(row=><tr className="hover:bg-brand-soft/40" key={row.rowNumber}>{shown.map(field=><td className="max-w-56 truncate whitespace-nowrap px-3 py-2.5" key={field} title={String(row.data[field]??"")}>{formatTableValue(row.data[field],result.fieldTypes?.[field])}</td>)}<td className="px-2"><button aria-label={`View row ${row.rowNumber}`} className="grid size-8 place-items-center rounded-lg text-text-secondary hover:bg-white hover:text-primary" onClick={()=>setSelected(row)} type="button"><Eye className="size-3.5"/></button></td></tr>)}</tbody></table>{!result.rows.length?<div className="grid min-h-40 place-items-center text-center"><div><p className="font-semibold">No matching records</p><p className="mt-1 text-xs text-text-secondary">Try clearing one or more filters.</p></div></div>:null}</div>
    <div className="flex items-center justify-between gap-3 border-t border-outline px-3 py-2"><p className="text-xs text-text-secondary">Page {result.pagination.page} of {result.pagination.totalPages}</p><div className="flex gap-1"><button aria-label="Previous page" className="grid size-8 place-items-center rounded-lg border border-outline disabled:opacity-40" disabled={result.pagination.page<=1} onClick={()=>onPageChange?.(result.pagination.page-1)} type="button"><ChevronLeft className="size-4"/></button><button aria-label="Next page" className="grid size-8 place-items-center rounded-lg border border-outline disabled:opacity-40" disabled={result.pagination.page>=result.pagination.totalPages} onClick={()=>onPageChange?.(result.pagination.page+1)} type="button"><ChevronRight className="size-4"/></button></div></div>
    {selected?<div className="fixed inset-0 z-50 bg-forest/40" onMouseDown={()=>setSelected(null)}><aside className="analytics-scrollbar absolute inset-y-0 right-0 w-full max-w-md overflow-y-auto bg-white p-5 shadow-analytics" onMouseDown={event=>event.stopPropagation()}><div className="flex items-center justify-between"><div><p className="analytics-kicker">Record details</p><h3 className="mt-1 font-heading text-xl font-semibold">Row {selected.rowNumber}</h3></div><button className="grid size-10 place-items-center rounded-lg hover:bg-background" onClick={()=>setSelected(null)} type="button"><X className="size-5"/></button></div><dl className="mt-5 divide-y divide-outline">{result.fields.map(field=><div className="grid gap-1 py-3 sm:grid-cols-[140px_1fr]" key={field}><dt className="text-xs font-semibold text-text-secondary">{labels[field]??field}</dt><dd className="break-words text-sm">{formatTableValue(selected.data[field],result.fieldTypes?.[field])}</dd></div>)}</dl></aside></div>:null}
  </div>;
}
