import { useMemo, useState, type FormEvent } from "react";
import { AdminModal } from "../AdminModal";
import type { AnalyticsColumn, AnalyticsSort, DashboardVisualizationSpec, SemanticModel, TimeGrain, VisualizationType } from "../../types/analytics";
const types:VisualizationType[]=["KPI","BAR","LINE","AREA","PIE","DONUT","SCATTER","TABLE","STACKED_BAR","STACKED_AREA"];
export function VisualizationEditor({item,semantic,columns,onClose,onApply}:{item:DashboardVisualizationSpec;semantic:SemanticModel;columns:AnalyticsColumn[];onClose:()=>void;onApply:(item:DashboardVisualizationSpec)=>void}){
  const[title,setTitle]=useState(item.title);const[type,setType]=useState(item.type);const[dimension,setDimension]=useState(item.dimension??"");const[measure,setMeasure]=useState(item.measure??"row_count");const[secondary,setSecondary]=useState(item.secondaryMeasure??"");const[stackBy,setStackBy]=useState(item.stackBy??"");const[aggregation,setAggregation]=useState<NonNullable<DashboardVisualizationSpec["aggregation"]>>(item.aggregation??"SUM");const[width,setWidth]=useState(item.layout.w);const[visible,setVisible]=useState(item.visible);const[topN,setTopN]=useState(item.topN??10);const[sort,setSort]=useState<AnalyticsSort>(item.sort??"VALUE_DESC");const[timeGrain,setTimeGrain]=useState<TimeGrain>(item.timeGrain??"AUTO");const[format,setFormat]=useState<NonNullable<DashboardVisualizationSpec["formatOverride"]>>(item.formatOverride??"AUTO");
  const dims=useMemo(()=>[...semantic.dimensions.map(value=>({field:value.field,label:value.label,date:false})),...semantic.dateFields.map(value=>({field:value.field,label:value.label,date:true}))],[semantic]);
  const measures=useMemo(()=>[...semantic.measures.map(value=>({id:value.id,label:value.label,aggregation:value.aggregation})),...semantic.calculatedMetrics.map(value=>({id:value.id,label:value.label,aggregation:"SUM"}))],[semantic]);
  const chosenDimension=dims.find(value=>value.field===dimension);const chart=!['KPI','TABLE'].includes(type);const stacked=['STACKED_BAR','STACKED_AREA'].includes(type);
  function compatible(candidate:VisualizationType){if(["LINE","AREA","STACKED_AREA"].includes(candidate)&&!semantic.dateFields.length)return false;if(candidate==="SCATTER"&&measures.length<2)return false;return true}
  function submit(event:FormEvent){event.preventDefault();const table=type==="TABLE";const kpi=type==="KPI";const selectedDimension=table||kpi?null:dimension||dims[0]?.field||null;onApply({...item,title:title.trim(),type,dimension:selectedDimension,measure:table?null:measure,secondaryMeasure:type==="SCATTER"?(secondary||(measures.find(value=>value.id!==measure)?.id??null)):null,aggregation:table?null:aggregation,stackBy:stacked?(stackBy||null):null,columns:table?(item.columns.length?item.columns:columns.slice(0,12).map(column=>column.normalizedName)):[],limit:table?25:Math.max(topN,item.limit),timeGrain:selectedDimension&&semantic.dateFields.some(value=>value.field===selectedDimension)?timeGrain:"AUTO",sort:selectedDimension&&semantic.dateFields.some(value=>value.field===selectedDimension)?"TIME_ASC":sort,topN,showOther:table||kpi?false:item.showOther??true,formatOverride:format,layout:{...item.layout,w:width},visible})}
  return <AdminModal description="Validated changes create a new immutable dashboard version. Canonical titles are reconciled on save." onClose={onClose} title="Edit visualization"><form className="space-y-4" onSubmit={submit}>
    <label className="block text-sm font-medium">Title<input className="mt-2 min-h-11 w-full rounded-xl border border-outline px-3" onChange={event=>setTitle(event.target.value)} required value={title}/></label>
    <label className="block text-sm font-medium">Chart type<select className="mt-2 min-h-11 w-full rounded-xl border border-outline bg-white px-3" onChange={event=>{const next=event.target.value as VisualizationType;setType(next);if(["LINE","AREA","STACKED_AREA"].includes(next)){const date=semantic.dateFields[0];if(date)setDimension(date.field)}}} value={type}>{types.map(value=><option disabled={!compatible(value)} key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></label>
    {chart?<label className="block text-sm font-medium">Dimension<select className="mt-2 min-h-11 w-full rounded-xl border border-outline bg-white px-3" onChange={event=>setDimension(event.target.value)} value={dimension}>{dims.map(value=><option disabled={["LINE","AREA","STACKED_AREA"].includes(type)&&!value.date} key={value.field} value={value.field}>{value.label}{value.date?" · date":""}</option>)}</select>{["PIE","DONUT"].includes(type)&&(columns.find(value=>value.normalizedName===dimension)?.uniqueCount??0)>12?<span className="mt-1 block text-xs text-warning">High-cardinality fields render better as a bar chart.</span>:null}</label>:null}
    {type!=="TABLE"?<><label className="block text-sm font-medium">Measure<select className="mt-2 min-h-11 w-full rounded-xl border border-outline bg-white px-3" onChange={event=>{setMeasure(event.target.value);const selected=measures.find(value=>value.id===event.target.value);if(selected)setAggregation(selected.aggregation as NonNullable<DashboardVisualizationSpec["aggregation"]>)}} value={measure}>{measures.map(value=><option key={value.id} value={value.id}>{value.label}</option>)}</select></label><label className="block text-sm font-medium">Aggregation<select className="mt-2 min-h-11 w-full rounded-xl border border-outline bg-white px-3" onChange={event=>setAggregation(event.target.value as NonNullable<DashboardVisualizationSpec["aggregation"]>)} value={aggregation}>{["SUM","AVG","MIN","MAX","COUNT"].map(value=><option key={value}>{value}</option>)}</select></label></>:null}
    {type==="SCATTER"?<label className="block text-sm font-medium">Secondary measure<select className="mt-2 min-h-11 w-full rounded-xl border border-outline bg-white px-3" onChange={event=>setSecondary(event.target.value)} value={secondary}>{measures.filter(value=>value.id!==measure).map(value=><option key={value.id} value={value.id}>{value.label}</option>)}</select></label>:null}
    {stacked?<label className="block text-sm font-medium">Stack by<select className="mt-2 min-h-11 w-full rounded-xl border border-outline bg-white px-3" onChange={event=>setStackBy(event.target.value)} value={stackBy}><option value="">No stack</option>{semantic.dimensions.filter(value=>value.field!==dimension).map(value=><option key={value.field} value={value.field}>{value.label}</option>)}</select></label>:null}
    {chart&&!chosenDimension?.date?<div className="grid grid-cols-2 gap-3"><label className="block text-sm font-medium">Top N<select className="mt-2 min-h-11 w-full rounded-xl border border-outline bg-white px-3" onChange={event=>setTopN(Number(event.target.value))} value={topN}>{[5,10,20,50].map(value=><option key={value} value={value}>{value}</option>)}</select></label><label className="block text-sm font-medium">Sort<select className="mt-2 min-h-11 w-full rounded-xl border border-outline bg-white px-3" onChange={event=>setSort(event.target.value as AnalyticsSort)} value={sort}>{["VALUE_DESC","VALUE_ASC","LABEL_ASC","LABEL_DESC"].map(value=><option key={value}>{value}</option>)}</select></label></div>:null}
    {chart&&chosenDimension?.date?<label className="block text-sm font-medium">Time grain<select className="mt-2 min-h-11 w-full rounded-xl border border-outline bg-white px-3" onChange={event=>setTimeGrain(event.target.value as TimeGrain)} value={timeGrain}>{["AUTO","DAY","WEEK","MONTH","QUARTER","YEAR"].map(value=><option key={value}>{value}</option>)}</select></label>:null}
    {type!=="TABLE"?<label className="block text-sm font-medium">Number format<select className="mt-2 min-h-11 w-full rounded-xl border border-outline bg-white px-3" onChange={event=>setFormat(event.target.value as NonNullable<DashboardVisualizationSpec["formatOverride"]>)} value={format}>{["AUTO","NUMBER","CURRENCY","PERCENTAGE"].map(value=><option key={value}>{value}</option>)}</select></label>:null}
    <label className="block text-sm font-medium">Grid width<select className="mt-2 min-h-11 w-full rounded-xl border border-outline bg-white px-3" onChange={event=>setWidth(Number(event.target.value))} value={width}>{[3,4,6,8,12].map(value=><option key={value} value={value}>{value} / 12 columns</option>)}</select></label>
    <label className="flex items-center gap-3 text-sm font-medium"><input checked={visible} className="size-4 accent-primary" onChange={event=>setVisible(event.target.checked)} type="checkbox"/>Visible on dashboard</label>
    <button className="min-h-12 w-full rounded-xl bg-primary text-sm font-semibold text-white" type="submit">Apply without AI</button>
  </form></AdminModal>;
}
