import {
  AlertTriangle,
  ArrowLeft,
  CheckCircle2,
  Copy,
  Laptop,
  RefreshCw,
  RotateCcw,
  Save,
  ShieldCheck,
  ShieldOff,
  UserCog,
} from "lucide-react";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";

import { AdminModal } from "../../components/AdminModal";
import {
  AdminApiError,
  getManagedAdmin,
  resetManagedAdminCredentials,
  revokeManagedAdminSessions,
  updateManagedAdminRole,
  updateManagedAdminStatus,
  verifyAdminStepUp,
} from "../../services/api";
import { useAdminStore } from "../../store/admin.store";
import type { AdminRole } from "../../types/admin";
import type { AdminAccountStatus, ManagedAdmin } from "../../types/governance";

const roles: AdminRole[] = ["SUPPORT_AGENT", "OPERATIONS_MANAGER", "FINANCE_MANAGER", "AUDITOR", "SUPER_ADMIN"];
const statusStyle: Record<AdminAccountStatus, string> = { active: "bg-green-50 text-primary", invited: "bg-blue-50 text-secondary", suspended: "bg-amber-50 text-warning", disabled: "bg-red-50 text-error" };
function date(value: string | null | undefined) { return value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Never"; }
function label(value: string) { return value.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase()); }
type Action = "role" | "status" | "reset" | "sessions";

export function AdminUserDetailPage() {
  const { id } = useParams(); const navigate = useNavigate(); const current = useAdminStore((state) => state.admin); const csrfToken = useAdminStore((state) => state.csrfToken); const clearSession = useAdminStore((state) => state.clearSession);
  const [admin, setAdmin] = useState<ManagedAdmin | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [action, setAction] = useState<Action | null>(null); const [credential, setCredential] = useState<string | null>(null);
  const load = useCallback(async () => { if (!id) return; setLoading(true); setError(""); try { const result = await getManagedAdmin(id); setAdmin(result.admin); } catch (requestError) { if (requestError instanceof AdminApiError && requestError.status === 401) { clearSession(); navigate("/login", { replace: true }); return; } setError(requestError instanceof Error ? requestError.message : "Unable to load administrator"); } finally { setLoading(false); } }, [clearSession, id, navigate]);
  useEffect(() => { void load(); }, [load]);
  if (loading && !admin) return <main className="grid min-h-[70vh] place-items-center"><RefreshCw className="size-8 animate-spin text-primary" /></main>;
  if (!admin) return <main className="grid min-h-[70vh] place-items-center p-6 text-center"><div><AlertTriangle className="mx-auto size-10 text-error" /><h1 className="mt-4 font-heading text-2xl font-semibold">Administrator unavailable</h1><p className="mt-2 text-sm text-text-secondary">{error}</p></div></main>;
  const canManage = current?.role === "SUPER_ADMIN" && current.id !== admin.id;
  return <main className="px-4 py-7 sm:px-6 lg:px-8 lg:py-10"><div className="mx-auto max-w-7xl">
    <Link className="inline-flex items-center gap-2 text-sm font-semibold text-primary" to="/admins"><ArrowLeft className="size-4" /> Administrator directory</Link>
    <section className="mt-5 flex flex-col gap-5 rounded-3xl bg-white p-6 shadow-card lg:flex-row lg:items-start lg:justify-between lg:p-8"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs font-semibold capitalize ${statusStyle[admin.status]}`}>{admin.status}</span><span className="rounded-full bg-background px-3 py-1 text-xs font-semibold">{label(admin.role)}</span>{current?.id === admin.id ? <span className="rounded-full bg-forest px-3 py-1 text-xs font-semibold text-white">Current account</span> : null}</div><h1 className="mt-4 font-heading text-3xl font-semibold">{admin.name}</h1><p className="mt-2 text-sm text-text-secondary">{admin.email}</p><p className="mt-1 font-mono text-xs text-text-secondary">{admin.id}</p></div>{canManage ? <div className="flex flex-wrap gap-2"><button className="action-btn" onClick={() => setAction("role")} type="button"><UserCog className="size-4" />Change role</button><button className="action-btn" onClick={() => setAction("status")} type="button"><ShieldOff className="size-4" />Change status</button><button className="action-btn" onClick={() => setAction("sessions")} type="button"><Laptop className="size-4" />Revoke sessions</button><button className="action-btn border-red-200 text-error" onClick={() => setAction("reset")} type="button"><RotateCcw className="size-4" />Reset credentials</button></div> : null}</section>
    {notice ? <div className="mt-5 flex gap-3 rounded-xl bg-green-50 p-4 text-sm text-primary" role="status"><CheckCircle2 className="size-5" />{notice}</div> : null}{error ? <div className="mt-5 flex gap-3 rounded-xl bg-red-50 p-4 text-sm text-error"><AlertTriangle className="size-5" />{error}</div> : null}
    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><div className="space-y-6"><section className="rounded-2xl border border-outline/70 bg-white p-5 shadow-card sm:p-6"><div className="flex items-center gap-3"><ShieldCheck className="size-5 text-primary" /><h2 className="font-heading text-xl font-semibold">Effective permissions</h2></div><div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{admin.permissions.map((permission) => <div className="flex items-center gap-2 rounded-xl bg-background p-3 text-sm" key={permission}><CheckCircle2 className="size-4 shrink-0 text-primary" /><span>{permission}</span></div>)}</div></section>
    <section className="rounded-2xl border border-outline/70 bg-white p-5 shadow-card sm:p-6"><div className="flex items-center justify-between"><div><p className="text-sm text-text-secondary">Latest 25 records</p><h2 className="font-heading text-xl font-semibold">Session history</h2></div><Link className="text-sm font-semibold text-primary" to={`/sessions?adminUserId=${admin.id}`}>Full explorer</Link></div><div className="mt-5 space-y-3">{admin.sessions?.length ? admin.sessions.map((session) => <article className="rounded-xl border border-outline/70 p-4" key={session.id}><div className="flex flex-wrap items-center justify-between gap-3"><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold capitalize ${session.state === "active" ? "bg-green-50 text-primary" : session.state === "revoked" ? "bg-red-50 text-error" : "bg-gray-100 text-text-secondary"}`}>{session.state}</span><span className="text-xs text-text-secondary">Last seen {date(session.lastSeenAt)}</span></div><p className="mt-3 break-all font-mono text-[11px] text-text-secondary">{session.id}</p><p className="mt-2 text-xs text-text-secondary">{session.ipAddress ?? "Unknown IP"} · {session.userAgent?.slice(0, 90) ?? "Unknown client"}</p>{session.revocationReason ? <p className="mt-2 rounded-lg bg-red-50 p-2 text-xs text-red-800">{session.revocationReason}</p> : null}</article>) : <p className="py-8 text-center text-sm text-text-secondary">No sessions recorded.</p>}</div></section></div>
    <aside className="space-y-6"><section className="rounded-2xl border border-outline/70 bg-white p-5 shadow-card"><h2 className="font-heading text-xl font-semibold">Security posture</h2><dl className="mt-5 space-y-4"><Info label="TOTP enrollment" value={admin.totpVerifiedAt ? `Verified ${date(admin.totpVerifiedAt)}` : "Pending"} /><Info label="Password changed" value={date(admin.passwordChangedAt)} /><Info label="Unused backup codes" value={String(admin.backupCodes?.unused ?? 0)} /><Info label="Failed login attempts" value={String(admin.failedLoginAttempts)} /><Info label="Locked until" value={date(admin.lockedUntil)} /></dl></section><section className="rounded-2xl border border-outline/70 bg-white p-5 shadow-card"><h2 className="font-heading text-xl font-semibold">Lifecycle</h2><dl className="mt-5 space-y-4"><Info label="Invited" value={date(admin.invitedAt)} /><Info label="Invited by" value={admin.invitedBy?.name ?? "Bootstrap / system"} /><Info label="Credentials reset" value={date(admin.credentialsResetAt)} /><Info label="Last login" value={date(admin.lastLoginAt)} /><Info label="Created" value={date(admin.createdAt)} /></dl></section></aside></div>
  </div>{action ? <ActionModal action={action} admin={admin} csrfToken={csrfToken} onClose={() => setAction(null)} onComplete={async (message, temporaryPassword) => { setAction(null); setNotice(message); if (temporaryPassword) setCredential(temporaryPassword); await load(); }} /> : null}{credential ? <AdminModal description="This reset password is returned once. Store and deliver it through an approved out-of-band channel." onClose={() => setCredential(null)} title="One-time reset credential"><div className="break-all rounded-xl bg-background p-4 font-mono font-semibold">{credential}</div><button className="action-btn mt-4 w-full justify-center" onClick={() => void navigator.clipboard.writeText(credential)} type="button"><Copy className="size-4" />Copy temporary password</button><button className="mt-3 min-h-12 w-full rounded-xl bg-primary text-sm font-semibold text-white" onClick={() => setCredential(null)} type="button">Stored securely</button></AdminModal> : null}</main>;
}

function ActionModal({ action, admin, csrfToken, onClose, onComplete }: { action: Action; admin: ManagedAdmin; csrfToken: string | null; onClose: () => void; onComplete: (message: string, password?: string) => Promise<void> }) {
  const [role, setRole] = useState<AdminRole>(admin.role); const [status, setStatus] = useState<Exclude<AdminAccountStatus, "invited">>(admin.status === "invited" ? "active" : admin.status); const [reason, setReason] = useState(""); const [code, setCode] = useState(""); const [working, setWorking] = useState(false); const [error, setError] = useState("");
  const names = { role: "Change administrator role", status: "Change account status", reset: "Reset credentials and MFA", sessions: "Revoke active sessions" };
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!csrfToken) return; setWorking(true); setError(""); try { await verifyAdminStepUp(csrfToken, code); if (action === "role") await updateManagedAdminRole(csrfToken, admin.id, role, reason); else if (action === "status") await updateManagedAdminStatus(csrfToken, admin.id, status, reason); else if (action === "sessions") { const result = await revokeManagedAdminSessions(csrfToken, admin.id, reason); await onComplete(`${result.revokedCount} active sessions revoked.`); return; } else { const result = await resetManagedAdminCredentials(csrfToken, admin.id, reason); await onComplete("Credentials, TOTP, backup codes, and sessions were reset.", result.temporaryPassword); return; } await onComplete(`Administrator ${action} change completed and audited.`); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Admin action failed"); } finally { setWorking(false); } }
  return <AdminModal description="This operation requires a fresh authenticator code, revokes affected access when necessary, and records the reason." onClose={() => !working && onClose()} title={names[action]}><form className="space-y-4" onSubmit={submit}>{error ? <div className="flex gap-3 rounded-xl bg-red-50 p-3 text-sm text-error"><AlertTriangle className="size-5" />{error}</div> : null}{action === "role" ? <label className="block text-sm font-medium">New role<select className="mt-2 min-h-12 w-full rounded-xl border border-outline bg-white px-3" onChange={(event) => setRole(event.target.value as AdminRole)} value={role}>{roles.map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></label> : null}{action === "status" ? <label className="block text-sm font-medium">New status<select className="mt-2 min-h-12 w-full rounded-xl border border-outline bg-white px-3" onChange={(event) => setStatus(event.target.value as Exclude<AdminAccountStatus, "invited">)} value={status}>{["active", "suspended", "disabled"].map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></label> : null}{action === "reset" ? <div className="rounded-xl bg-red-50 p-4 text-sm leading-6 text-red-900">All sessions, login challenges, backup codes, password, and TOTP enrollment will be replaced. The account returns to invited state.</div> : null}<label className="block text-sm font-medium">Private audit reason<textarea className="mt-2 min-h-24 w-full rounded-xl border border-outline p-3" maxLength={500} minLength={10} onChange={(event) => setReason(event.target.value)} required value={reason} /></label><label className="block text-sm font-medium">Authenticator code<input className="mt-2 min-h-12 w-full rounded-xl border border-outline px-3 font-mono tracking-[0.3em]" inputMode="numeric" maxLength={6} onChange={(event) => setCode(event.target.value.replace(/\D/g, ""))} required value={code} /></label><button className={`inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl text-sm font-semibold text-white disabled:opacity-60 ${action === "reset" || action === "sessions" ? "bg-error" : "bg-primary"}`} disabled={working} type="submit"><Save className="size-4" />{working ? "Verifying and applying…" : "Confirm audited action"}</button></form></AdminModal>;
}
function Info({ label: name, value }: { label: string; value: string }) { return <div><dt className="text-xs text-text-secondary">{name}</dt><dd className="mt-1 break-words font-medium">{value}</dd></div>; }
