import {
  AlertTriangle,
  CheckCircle2,
  KeyRound,
  LockKeyhole,
  Mail,
  RefreshCw,
  Save,
  ServerCog,
  ShieldCheck,
  Timer,
  WalletCards,
} from "lucide-react";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { useNavigate } from "react-router-dom";

import { AdminModal } from "../../components/AdminModal";
import {
  AdminApiError,
  getAdminSystemSettings,
  updateAdminSystemSettings,
  verifyAdminStepUp,
} from "../../services/api";
import { useAdminStore } from "../../store/admin.store";
import type { PlatformSetting, SecurityBaseline } from "../../types/governance";

function currency(value: number) { return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 }).format(value); }

export function AdminSettingsPage() {
  const navigate = useNavigate(); const csrfToken = useAdminStore((state) => state.csrfToken); const clearSession = useAdminStore((state) => state.clearSession); const [setting, setSetting] = useState<PlatformSetting | null>(null); const [baseline, setBaseline] = useState<SecurityBaseline | null>(null); const [draft, setDraft] = useState<PlatformSetting | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [confirming, setConfirming] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const result = await getAdminSystemSettings(); setSetting(result.setting); setDraft(result.setting); setBaseline(result.securityBaseline); } catch (requestError) { if (requestError instanceof AdminApiError && requestError.status === 401) { clearSession(); navigate("/login", { replace: true }); return; } setError(requestError instanceof Error ? requestError.message : "Unable to load system settings"); } finally { setLoading(false); } }, [clearSession, navigate]);
  useEffect(() => { void load(); }, [load]);
  if (loading && !draft) return <main className="grid min-h-[70vh] place-items-center"><RefreshCw className="size-8 animate-spin text-primary" /></main>;
  if (!draft || !baseline) return <main className="grid min-h-[70vh] place-items-center p-6 text-center"><div><AlertTriangle className="mx-auto size-10 text-error" /><h1 className="mt-4 font-heading text-2xl font-semibold">Settings unavailable</h1><p className="mt-2 text-sm text-text-secondary">{error}</p></div></main>;
  const changed = setting && JSON.stringify({ ...setting, updatedAt: undefined, updatedByAdminId: undefined }) !== JSON.stringify({ ...draft, updatedAt: undefined, updatedByAdminId: undefined });
  return <main className="px-4 py-7 sm:px-6 lg:px-8 lg:py-10"><div className="mx-auto max-w-7xl"><div><p className="text-sm text-text-secondary">Enforced platform controls</p><h1 className="mt-1 font-heading text-3xl font-semibold">System and security settings</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-text-secondary">Changes are stored in PostgreSQL, enforced by customer authentication/payment middleware, protected by TOTP step-up, and appended to the audit log.</p></div>
    {notice ? <div className="mt-5 flex gap-3 rounded-xl bg-green-50 p-4 text-sm text-primary"><CheckCircle2 className="size-5" />{notice}</div> : null}{error ? <div className="mt-5 flex gap-3 rounded-xl bg-red-50 p-4 text-sm text-error"><AlertTriangle className="size-5" />{error}</div> : null}
    <div className="mt-7 grid gap-6 xl:grid-cols-[minmax(0,1fr)_420px]"><section className="rounded-2xl border border-outline/70 bg-white p-5 shadow-card sm:p-6"><div className="flex items-center gap-3"><ServerCog className="size-5 text-primary" /><div><p className="text-sm text-text-secondary">Runtime feature gates</p><h2 className="font-heading text-xl font-semibold">Customer platform controls</h2></div></div><div className="mt-6 space-y-4"><Toggle checked={draft.maintenanceMode} description="Returns HTTP 503 for customer APIs while all admin APIs remain operational." label="Maintenance mode" onChange={(value) => setDraft({ ...draft, maintenanceMode: value })} warning /><Toggle checked={draft.customerRegistrationEnabled} description="Controls creation of new customer identities." label="Customer registration" onChange={(value) => setDraft({ ...draft, customerRegistrationEnabled: value })} /><Toggle checked={draft.customerOtpLoginEnabled} description="Controls both OTP challenge delivery and verification." label="Customer OTP login" onChange={(value) => setDraft({ ...draft, customerOtpLoginEnabled: value })} /><Toggle checked={draft.walletRechargeEnabled} description="Controls development-provider wallet recharge creation." label="Wallet recharge" onChange={(value) => setDraft({ ...draft, walletRechargeEnabled: value })} /></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium"><span className="flex items-center gap-2"><Mail className="size-4 text-primary" />Support email</span><input className="mt-2 min-h-12 w-full rounded-xl border border-outline px-3" onChange={(event) => setDraft({ ...draft, supportEmail: event.target.value || null })} type="email" value={draft.supportEmail ?? ""} /></label><label className="block text-sm font-medium"><span className="flex items-center gap-2"><WalletCards className="size-4 text-primary" />Maximum recharge</span><input className="mt-2 min-h-12 w-full rounded-xl border border-outline px-3" max="500000" min="1" onChange={(event) => setDraft({ ...draft, maxRechargeAmount: Number(event.target.value) })} step="0.01" type="number" value={draft.maxRechargeAmount} /><span className="mt-1 block text-xs text-text-secondary">Current limit: {currency(draft.maxRechargeAmount || 0)}</span></label></div><button className="mt-6 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-primary text-sm font-semibold text-white disabled:opacity-50" disabled={!changed} onClick={() => setConfirming(true)} type="button"><Save className="size-4" />Review and save changes</button></section>
    <aside className="space-y-6"><section className="rounded-2xl bg-forest p-5 text-white shadow-card"><div className="flex items-center gap-3"><ShieldCheck className="size-5 text-green-300" /><h2 className="font-heading text-xl font-semibold">Security baseline</h2></div><div className="mt-5 grid grid-cols-2 gap-3"><Baseline icon={Timer} label="Session lifetime" value={`${baseline.adminSessionHours} hours`} /><Baseline icon={KeyRound} label="Step-up window" value={`${baseline.stepUpWindowMinutes} min`} /><Baseline icon={LockKeyhole} label="Login lock" value={`${baseline.maximumLoginFailures} failures`} /><Baseline icon={KeyRound} label="TOTP" value={`${baseline.totpDigits} digits / ${baseline.totpPeriodSeconds}s`} /></div></section><section className="rounded-2xl border border-outline/70 bg-white p-5 shadow-card"><h2 className="font-heading text-xl font-semibold">Hardening status</h2><div className="mt-5 space-y-3"><Check text="Database-level append-only audit trigger" active={baseline.auditDatabaseAppendOnly} /><Check text="Helmet security headers and production HSTS" active={baseline.securityHeadersEnabled} /><Check text="Global, admin-login, MFA, and OTP rate limits" active={baseline.rateLimitingEnabled} /><Check text="HttpOnly, SameSite=Strict admin cookie" active={baseline.adminCookieHttpOnly} /><Check text="Secure cookie required in production" active={baseline.adminCookieSecureInProduction} /></div></section><section className="rounded-2xl border border-outline/70 bg-white p-5 text-sm text-text-secondary shadow-card"><p>Operational security constants are read-only here and changed through reviewed deployment configuration. Feature gates are the only database-controlled settings.</p>{setting?.updatedAt ? <p className="mt-3 text-xs">Last database update: {new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(setting.updatedAt))}</p> : null}</section></aside></div>
  </div>{confirming ? <ConfirmModal csrfToken={csrfToken} draft={draft} onClose={() => setConfirming(false)} onComplete={async (updated) => { setConfirming(false); setSetting(updated); setDraft(updated); setNotice("System settings updated, enforced, and audited."); }} /> : null}</main>;
}

function ConfirmModal({ csrfToken, draft, onClose, onComplete }: { csrfToken: string | null; draft: PlatformSetting; onClose: () => void; onComplete: (setting: PlatformSetting) => Promise<void> }) { const [reason, setReason] = useState(""); const [code, setCode] = useState(""); const [working, setWorking] = useState(false); const [error, setError] = useState(""); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!csrfToken) return; setWorking(true); setError(""); try { await verifyAdminStepUp(csrfToken, code); const result = await updateAdminSystemSettings(csrfToken, { supportEmail: draft.supportEmail, maintenanceMode: draft.maintenanceMode, customerRegistrationEnabled: draft.customerRegistrationEnabled, customerOtpLoginEnabled: draft.customerOtpLoginEnabled, walletRechargeEnabled: draft.walletRechargeEnabled, maxRechargeAmount: draft.maxRechargeAmount, reason }); await onComplete(result.setting); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to update settings"); } finally { setWorking(false); } } return <AdminModal description="These controls immediately affect customer API availability. The previous and next values are stored in append-only audit metadata." onClose={() => !working && onClose()} title="Confirm system settings"><form className="space-y-4" onSubmit={submit}>{draft.maintenanceMode ? <div className="rounded-xl bg-red-50 p-4 text-sm leading-6 text-red-900"><strong>Maintenance mode will be enabled.</strong> Customer APIs will return HTTP 503 until it is disabled.</div> : null}{error ? <div className="rounded-xl bg-red-50 p-3 text-sm text-error">{error}</div> : null}<label className="block text-sm font-medium">Private audit reason<textarea className="mt-2 min-h-24 w-full rounded-xl border border-outline p-3" minLength={10} onChange={(event) => setReason(event.target.value)} required value={reason} /></label><label className="block text-sm font-medium">Authenticator code<input className="mt-2 min-h-12 w-full rounded-xl border border-outline px-3 font-mono tracking-[0.3em]" inputMode="numeric" maxLength={6} onChange={(event) => setCode(event.target.value.replace(/\D/g, ""))} required value={code} /></label><button className="min-h-12 w-full rounded-xl bg-primary text-sm font-semibold text-white disabled:opacity-60" disabled={working} type="submit">{working ? "Verifying and saving…" : "Apply audited settings"}</button></form></AdminModal>; }
function Toggle({ checked, description, label, onChange, warning = false }: { checked: boolean; description: string; label: string; onChange: (value: boolean) => void; warning?: boolean }) { return <label className={`flex cursor-pointer items-start justify-between gap-4 rounded-xl border p-4 ${warning && checked ? "border-red-200 bg-red-50" : "border-outline"}`}><span><span className="block font-semibold">{label}</span><span className="mt-1 block text-xs leading-5 text-text-secondary">{description}</span></span><input checked={checked} className="mt-1 size-5 accent-green-600" onChange={(event) => onChange(event.target.checked)} type="checkbox" /></label>; }
function Baseline({ icon: Icon, label, value }: { icon: typeof Timer; label: string; value: string }) { return <div className="rounded-xl bg-white/10 p-3"><Icon className="size-4 text-green-300" /><p className="mt-2 text-[10px] text-white/60">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>; }
function Check({ active, text }: { active: boolean; text: string }) { return <div className="flex items-start gap-3 text-sm"><CheckCircle2 className={`mt-0.5 size-4 shrink-0 ${active ? "text-primary" : "text-text-secondary"}`} /><span>{text}</span></div>; }
