import {
  AlertTriangle,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  Clock3,
  Headset,
  RefreshCw,
  Search,
  UserMinus,
  type LucideIcon,
} from "lucide-react";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Link, useNavigate } from "react-router-dom";

import {
  AdminApiError,
  getAdminTicketSummary,
  listAdminTickets,
} from "../../services/api";
import { useAdminStore } from "../../store/admin.store";
import type { CustomerPagination } from "../../types/customer";
import type { AdminTicket, TicketPriority, TicketStatus, TicketSummary } from "../../types/ticket";

const statusStyles: Record<TicketStatus,string>={open:"bg-blue-50 text-secondary",in_progress:"bg-amber-50 text-warning",resolved:"bg-green-50 text-primary",closed:"bg-gray-100 text-text-secondary"};
const priorityStyles: Record<TicketPriority,string>={low:"bg-gray-100 text-text-secondary",normal:"bg-blue-50 text-secondary",high:"bg-amber-50 text-warning",critical:"bg-red-50 text-error"};
const ticketTypes: Array<[string,string]>=[["ACCIDENT","Accident"],["HEALTH_ISSUE","Health issue"],["LEASE_PAUSE","Lease pause"],["NOC_TRANSFER","NOC / Transfer"],["COMPLAINT","Complaint"],["FORECLOSURE","Foreclosure"],["REPORT_ISSUE","App issue"],["OTHER","Other"]];

function slaText(ticket:AdminTicket){if(!ticket.slaDueAt)return "No SLA";if(ticket.status==="resolved"||ticket.status==="closed")return "Completed";const diff=new Date(ticket.slaDueAt).getTime()-Date.now();if(diff<0)return `${Math.ceil(Math.abs(diff)/3600000)}h overdue`;if(diff<3600000)return `${Math.max(1,Math.ceil(diff/60000))}m left`;return `${Math.ceil(diff/3600000)}h left`;}
function isOverdue(ticket:AdminTicket){return Boolean(ticket.slaDueAt&&new Date(ticket.slaDueAt)<new Date()&&["open","in_progress"].includes(ticket.status));}

export function AdminTicketsPage(){
 const navigate=useNavigate();const clearSession=useAdminStore(s=>s.clearSession);const [tickets,setTickets]=useState<AdminTicket[]>([]);const [summary,setSummary]=useState<TicketSummary|null>(null);const [pagination,setPagination]=useState<CustomerPagination>({page:1,pageSize:20,total:0,totalPages:1});const [searchInput,setSearchInput]=useState("");const [query,setQuery]=useState("");const [status,setStatus]=useState("");const [priority,setPriority]=useState("");const [type,setType]=useState("");const [assignment,setAssignment]=useState("all");const [page,setPage]=useState(1);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [list,stats]=await Promise.all([listAdminTickets({q:query,status,priority,type,assignment,page,pageSize:20}),getAdminTicketSummary()]);setTickets(list.tickets);setPagination(list.pagination);setSummary(stats.summary);}catch(e){if(e instanceof AdminApiError&&e.status===401){clearSession();navigate('/login',{replace:true});return;}setError(e instanceof Error?e.message:"Unable to load tickets");}finally{setLoading(false);}},[assignment,clearSession,navigate,page,priority,query,status,type]);useEffect(()=>{void load();},[load]);
 function search(e:FormEvent){e.preventDefault();setPage(1);setQuery(searchInput.trim());}
 const cards: Array<[string,number,LucideIcon]>=summary?[["Open",summary.open,Headset],["In progress",summary.inProgress,Clock3],["Overdue",summary.overdue,AlertTriangle],["Critical",summary.critical,AlertTriangle],["Unassigned",summary.unassigned,UserMinus],["Resolved today",summary.resolvedToday,CheckCircle2]]:[];
 return <main className="px-4 py-7 sm:px-6 lg:px-8 lg:py-10"><div className="mx-auto max-w-7xl">
  <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm text-text-secondary">Customer support operations</p><h1 className="mt-1 font-heading text-3xl font-semibold">Support ticket queue</h1><p className="mt-2 text-sm text-text-secondary">Prioritize, assign, respond, resolve, and audit every customer request.</p></div><span className="w-fit rounded-xl bg-white px-4 py-3 text-sm font-semibold shadow-card">{pagination.total} tickets</span></div>
  <section className="mt-7 grid grid-cols-2 gap-4 md:grid-cols-3 xl:grid-cols-6">{cards.map(([label,value,Icon])=><article className="rounded-2xl border border-outline/70 bg-white p-5 shadow-card" key={String(label)}><Icon className="size-5 text-primary"/><p className="mt-3 text-sm text-text-secondary">{String(label)}</p><p className="mt-1 font-heading text-2xl font-semibold">{String(value)}</p></article>)}</section>
  {error?<div className="mt-5 flex justify-between rounded-xl bg-red-50 p-4 text-sm text-error"><span>{error}</span><button onClick={()=>void load()} type="button"><RefreshCw className="size-4"/></button></div>:null}
  <section className="mt-6 rounded-2xl border border-outline/70 bg-white p-4 shadow-card"><form className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_150px_150px_170px_160px_auto]" onSubmit={search}><label className="relative"><Search className="pointer-events-none absolute left-4 top-1/2 size-5 -translate-y-1/2 text-text-secondary"/><input className="min-h-12 w-full rounded-xl border border-outline py-3 pl-12 pr-3" onChange={e=>setSearchInput(e.target.value)} placeholder="Ticket, customer, phone or serial" value={searchInput}/></label><Filter label="All statuses" onChange={v=>{setStatus(v);setPage(1)}} options={[["open","Open"],["in_progress","In progress"],["resolved","Resolved"],["closed","Closed"]]} value={status}/><Filter label="All priorities" onChange={v=>{setPriority(v);setPage(1)}} options={[["low","Low"],["normal","Normal"],["high","High"],["critical","Critical"]]} value={priority}/><Filter label="All ticket types" onChange={v=>{setType(v);setPage(1)}} options={ticketTypes} value={type}/><Filter label="All assignments" onChange={v=>{setAssignment(v);setPage(1)}} options={[["mine","Assigned to me"],["unassigned","Unassigned"],["all","All assignments"]]} value={assignment}/><button className="min-h-12 rounded-xl bg-primary px-5 text-sm font-semibold text-white" type="submit">Search</button></form></section>
  <section className="mt-6 overflow-hidden rounded-2xl border border-outline/70 bg-white shadow-card">{loading?<div className="space-y-3 p-5">{Array.from({length:6},(_,i)=><div className="h-16 animate-pulse rounded-xl bg-background" key={i}/>)}</div>:tickets.length===0?<div className="py-16 text-center"><Headset className="mx-auto size-10 text-text-secondary"/><h2 className="mt-4 font-heading text-xl font-semibold">No tickets found</h2></div>:<><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[1100px] text-left"><thead className="bg-background text-xs uppercase text-text-secondary"><tr><th className="p-4">Ticket / customer</th><th className="p-4">Type</th><th className="p-4">Priority</th><th className="p-4">Status</th><th className="p-4">Assignee</th><th className="p-4">SLA</th><th className="p-4"/></tr></thead><tbody className="divide-y divide-outline/60">{tickets.map(t=><tr className="hover:bg-background/60" key={t.id}><td className="p-4"><p className="font-semibold">{t.user.name}</p><p className="mt-1 font-mono text-xs text-text-secondary">#{t.id.slice(0,8).toUpperCase()} · {t.user.phone}</p></td><td className="p-4 text-sm">{t.type.replaceAll('_',' ')}</td><td className="p-4"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold capitalize ${priorityStyles[t.priority]}`}>{t.priority}</span></td><td className="p-4"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold capitalize ${statusStyles[t.status]}`}>{t.status.replaceAll('_',' ')}</span></td><td className="p-4 text-sm">{t.assignedAdmin?.name||<span className="text-text-secondary">Unassigned</span>}</td><td className={`p-4 text-sm font-semibold ${isOverdue(t)?"text-error":"text-text-secondary"}`}>{slaText(t)}</td><td className="p-4 text-right"><Link className="font-semibold text-primary" to={`/tickets/${t.id}`}>Open</Link></td></tr>)}</tbody></table></div><div className="divide-y divide-outline/60 md:hidden">{tickets.map(t=><Link className="block p-5" key={t.id} to={`/tickets/${t.id}`}><div className="flex justify-between gap-3"><div><p className="font-semibold">{t.user.name}</p><p className="mt-1 text-xs text-text-secondary">{t.type.replaceAll('_',' ')}</p></div><span className={`h-fit rounded-full px-2 py-1 text-[10px] font-semibold ${priorityStyles[t.priority]}`}>{t.priority}</span></div><div className="mt-3 flex justify-between text-xs text-text-secondary"><span>{t.status.replaceAll('_',' ')}</span><span className={isOverdue(t)?"text-error":""}>{slaText(t)}</span></div></Link>)}</div></>}</section>
  <div className="mt-6 flex items-center justify-between"><p className="text-sm text-text-secondary">Page {pagination.page} of {pagination.totalPages}</p><div className="flex gap-2"><button className="page-btn" disabled={page<=1||loading} onClick={()=>setPage(p=>p-1)} type="button"><ChevronLeft className="size-4"/> Previous</button><button className="page-btn" disabled={page>=pagination.totalPages||loading} onClick={()=>setPage(p=>p+1)} type="button">Next <ChevronRight className="size-4"/></button></div></div>
 </div></main>;
}
function Filter({label,onChange,options,value}:{label:string;onChange:(v:string)=>void;options:Array<[string,string]>;value:string}){return <select className="min-h-12 rounded-xl border border-outline bg-white px-3" onChange={e=>onChange(e.target.value)} value={value}><option value="">{label}</option>{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select>;}
