import {
  AlertCircle,
  ArrowLeft,
  CheckCircle2,
  Clock3,
  MessageSquarePlus,
  RefreshCw,
  Save,
  UserRound,
  X,
} from "lucide-react";
import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from "react";
import { Link, useParams } from "react-router-dom";

import {
  addAdminTicketNote,
  assignAdminTicket,
  getAdminTicket,
  getAdminTicketAssignees,
  updateAdminTicketPriority,
  updateAdminTicketStatus,
} from "../../services/api";
import { useAdminStore } from "../../store/admin.store";
import type { AdminTicketDetail, TicketAssignee, TicketPriority, TicketStatus } from "../../types/ticket";

const statusStyles:Record<string,string>={open:"bg-blue-50 text-secondary",in_progress:"bg-amber-50 text-warning",resolved:"bg-green-50 text-primary",closed:"bg-gray-100 text-text-secondary"};
const priorityStyles:Record<string,string>={low:"bg-gray-100 text-text-secondary",normal:"bg-blue-50 text-secondary",high:"bg-amber-50 text-warning",critical:"bg-red-50 text-error"};

type ModalAction="assign"|"priority"|"status";

export function AdminTicketDetailPage(){
 const {id}=useParams();const csrfToken=useAdminStore(s=>s.csrfToken);const [ticket,setTicket]=useState<AdminTicketDetail|null>(null);const [assignees,setAssignees]=useState<TicketAssignee[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [action,setAction]=useState<ModalAction|null>(null);const [assigneeId,setAssigneeId]=useState("");const [priority,setPriority]=useState<TicketPriority>("normal");const [targetStatus,setTargetStatus]=useState<TicketStatus>("in_progress");const [reason,setReason]=useState("");const [resolution,setResolution]=useState("");const [note,setNote]=useState("");const [working,setWorking]=useState(false);
 const load=useCallback(async()=>{if(!id)return;setLoading(true);setError("");try{const [t,a]=await Promise.all([getAdminTicket(id),getAdminTicketAssignees()]);setTicket(t.ticket);setAssignees(a.assignees);setAssigneeId(t.ticket.assignedAdminId??"");setPriority(t.ticket.priority);}catch(e){setError(e instanceof Error?e.message:"Unable to load ticket");}finally{setLoading(false);}},[id]);useEffect(()=>{void load();},[load]);useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(""),5000);return()=>clearTimeout(t);},[notice]);
 async function applyAction(e:FormEvent){e.preventDefault();if(!csrfToken||!id||!action)return;setWorking(true);setError("");try{if(action==="assign")await assignAdminTicket(csrfToken,id,assigneeId||null,reason);else if(action==="priority")await updateAdminTicketPriority(csrfToken,id,priority,reason);else await updateAdminTicketStatus(csrfToken,id,targetStatus,reason,resolution||undefined);setNotice(`Ticket ${action} action completed and audited.`);setAction(null);setReason("");setResolution("");await load();}catch(err){setError(err instanceof Error?err.message:"Ticket action failed");}finally{setWorking(false);}}
 async function addNote(e:FormEvent){e.preventDefault();if(!csrfToken||!id)return;setWorking(true);setError("");try{await addAdminTicketNote(csrfToken,id,note);setNote("");setNotice("Internal note added and audited.");await load();}catch(err){setError(err instanceof Error?err.message:"Unable to add note");}finally{setWorking(false);}}
 if(loading&&!ticket)return <main className="grid min-h-[70vh] place-items-center"><RefreshCw className="size-8 animate-spin text-primary"/></main>;
 if(!ticket)return <main className="p-10 text-center text-error">{error||"Ticket not found"}</main>;
 const overdue=Boolean(ticket.slaDueAt&&new Date(ticket.slaDueAt)<new Date()&&["open","in_progress"].includes(ticket.status));
 const nextStatuses:TicketStatus[]=ticket.status==="open"?["in_progress"]:ticket.status==="in_progress"?["resolved"]:ticket.status==="resolved"?["in_progress","closed"]:["in_progress"];
 return <main className="px-4 py-7 sm:px-6 lg:px-8 lg:py-10"><div className="mx-auto max-w-7xl">
  <Link className="inline-flex items-center gap-2 text-sm font-semibold text-primary" to="/tickets"><ArrowLeft className="size-4"/> Ticket queue</Link>
  <section className="mt-5 flex flex-col gap-5 rounded-3xl bg-white p-6 shadow-card lg:flex-row lg:items-start lg:justify-between lg:p-8"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs font-semibold capitalize ${priorityStyles[ticket.priority]}`}>{ticket.priority}</span><span className={`rounded-full px-3 py-1 text-xs font-semibold capitalize ${statusStyles[ticket.status]}`}>{ticket.status.replaceAll('_',' ')}</span>{overdue?<span className="rounded-full bg-red-50 px-3 py-1 text-xs font-semibold text-error">SLA overdue</span>:null}</div><h1 className="mt-4 font-heading text-3xl font-semibold">{ticket.type.replaceAll('_',' ')}</h1><p className="mt-2 font-mono text-xs text-text-secondary">#{ticket.id.toUpperCase()}</p></div><div className="flex flex-wrap gap-2"><button className="action-btn" onClick={()=>{setAction('assign');setReason('')}} type="button"><UserRound className="size-4"/> Assign</button><button className="action-btn" onClick={()=>{setAction('priority');setReason('')}} type="button"><AlertCircle className="size-4"/> Priority</button>{nextStatuses.map(s=><button className="action-btn" key={s} onClick={()=>{setTargetStatus(s);setAction('status');setReason('');setResolution(ticket.resolutionMessage??'')}} type="button">{s==='resolved'||s==='closed'?<CheckCircle2 className="size-4"/>:<Clock3 className="size-4"/>}{s.replaceAll('_',' ')}</button>)}</div></section>
  {notice?<div className="mt-5 flex gap-3 rounded-xl bg-green-50 p-4 text-sm text-primary"><CheckCircle2 className="size-5"/>{notice}</div>:null}{error?<div className="mt-5 flex gap-3 rounded-xl bg-red-50 p-4 text-sm text-error"><AlertCircle className="size-5"/>{error}</div>:null}
  <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_390px]"><div className="space-y-6"><section className="rounded-2xl border border-outline/70 bg-white p-6 shadow-card"><h2 className="font-heading text-xl font-semibold">Customer request</h2><p className="mt-4 whitespace-pre-wrap leading-7 text-text-primary">{ticket.description}</p>{ticket.resolutionMessage?<div className="mt-5 rounded-xl bg-green-50 p-4 text-sm leading-6 text-primary"><strong>Customer-visible resolution</strong><p className="mt-1">{ticket.resolutionMessage}</p></div>:null}</section>
  <section className="rounded-2xl border border-outline/70 bg-white p-6 shadow-card"><div className="flex items-center justify-between"><div><p className="text-sm text-text-secondary">Private admin collaboration</p><h2 className="font-heading text-xl font-semibold">Internal notes</h2></div><span className="rounded-full bg-background px-3 py-1 text-xs font-semibold">{ticket.notes.length}</span></div><form className="mt-5" onSubmit={addNote}><textarea className="min-h-24 w-full rounded-xl border border-outline p-3" onChange={e=>setNote(e.target.value)} placeholder="Add a private note (never visible to the customer)" required value={note}/><button className="mt-3 inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-white disabled:opacity-60" disabled={working} type="submit"><MessageSquarePlus className="size-4"/> Add internal note</button></form><div className="mt-6 space-y-3">{ticket.notes.length?ticket.notes.map(n=><article className="rounded-xl bg-background p-4" key={n.id}><div className="flex justify-between gap-3"><p className="font-semibold">{n.adminUser.name}</p><span className="text-xs text-text-secondary">{new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(n.createdAt))}</span></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-text-secondary">{n.body}</p></article>):<p className="py-5 text-center text-sm text-text-secondary">No internal notes.</p>}</div></section></div>
  <aside className="space-y-6"><section className="rounded-2xl border border-outline/70 bg-white p-5 shadow-card"><h2 className="font-heading text-xl font-semibold">Customer</h2><Link className="mt-4 block rounded-xl bg-background p-4" to={`/customers/${ticket.user.id}`}><p className="font-semibold">{ticket.user.name}</p><p className="mt-1 text-sm text-text-secondary">{ticket.user.phone}</p><p className="mt-2 text-xs capitalize text-primary">{ticket.user.accountStatus}</p></Link></section>{ticket.asset?<section className="rounded-2xl border border-outline/70 bg-white p-5 shadow-card"><h2 className="font-heading text-xl font-semibold">Related asset</h2><Link className="mt-4 block rounded-xl bg-background p-4" to={`/inventory/${ticket.asset.id}`}><p className="font-semibold">{ticket.asset.productType}</p><p className="mt-1 font-mono text-xs text-text-secondary">{ticket.asset.serialNumber}</p></Link></section>:null}<section className="rounded-2xl border border-outline/70 bg-white p-5 shadow-card"><h2 className="font-heading text-xl font-semibold">Service timeline</h2><dl className="mt-4 space-y-4"><Info label="Created" value={date(ticket.createdAt)}/><Info label="SLA due" value={ticket.slaDueAt?date(ticket.slaDueAt):"Not set"}/><Info label="First response" value={ticket.firstResponseAt?date(ticket.firstResponseAt):"Pending"}/><Info label="Resolved" value={ticket.resolvedAt?date(ticket.resolvedAt):"Pending"}/></dl></section><section className="rounded-2xl border border-outline/70 bg-white p-5 shadow-card"><h2 className="font-heading text-xl font-semibold">Assignment</h2><p className="mt-4 text-sm">{ticket.assignedAdmin?.name||"Unassigned"}</p>{ticket.assignedAdmin?<p className="mt-1 text-xs text-text-secondary">{ticket.assignedAdmin.role.replaceAll('_',' ')}</p>:null}</section></aside></div>
 </div>
 {action?<Modal title={action==='assign'?'Assign ticket':action==='priority'?'Change priority':'Change ticket status'} onClose={()=>!working&&setAction(null)}><form className="space-y-4" onSubmit={applyAction}>{error?<div className="rounded-xl bg-red-50 p-3 text-sm text-error">{error}</div>:null}{action==='assign'?<label className="block text-sm font-medium">Assignee<select className="mt-2 min-h-12 w-full rounded-xl border border-outline bg-white px-3" onChange={e=>setAssigneeId(e.target.value)} value={assigneeId}><option value="">Unassigned</option>{assignees.map(a=><option key={a.id} value={a.id}>{a.name} · {a.role.replaceAll('_',' ')}</option>)}</select></label>:null}{action==='priority'?<label className="block text-sm font-medium">Priority<select className="mt-2 min-h-12 w-full rounded-xl border border-outline bg-white px-3" onChange={e=>setPriority(e.target.value as TicketPriority)} value={priority}>{['low','normal','high','critical'].map(p=><option key={p} value={p}>{p}</option>)}</select></label>:null}{action==='status'?<><div className="rounded-xl bg-background p-4 text-sm">Transition: <strong>{ticket.status.replaceAll('_',' ')}</strong> → <strong>{targetStatus.replaceAll('_',' ')}</strong></div>{['resolved','closed'].includes(targetStatus)?<label className="block text-sm font-medium">Customer-visible resolution<textarea className="mt-2 min-h-28 w-full rounded-xl border border-outline p-3" onChange={e=>setResolution(e.target.value)} required value={resolution}/></label>:null}</>:null}<label className="block text-sm font-medium">Audit reason<textarea className="mt-2 min-h-24 w-full rounded-xl border border-outline p-3" onChange={e=>setReason(e.target.value)} required value={reason}/></label><button className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-primary text-sm font-semibold text-white disabled:opacity-60" disabled={working} type="submit"><Save className="size-4"/>{working?"Saving…":"Save audited change"}</button></form></Modal>:null}
 </main>;
}
function date(v:string){return new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));}
function Info({label,value}:{label:string;value:string}){return <div><dt className="text-xs text-text-secondary">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>;}
function Modal({children,onClose,title}:{children:ReactNode;onClose:()=>void;title:string}){return <div className="fixed inset-0 z-50 grid place-items-center bg-black/45 p-4 backdrop-blur-sm"><section className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between gap-3"><h2 className="font-heading text-2xl font-semibold">{title}</h2><button className="grid size-10 place-items-center rounded-full hover:bg-background" onClick={onClose} type="button"><X className="size-5"/></button></div><div className="mt-5">{children}</div></section></div>;}
