import { Prisma } from "@prisma/client";
import { prisma } from "../../database/prisma.js";
import { ApiError } from "../../middleware/error.middleware.js";
import type { AdminRequestContext } from "../admin-auth/admin-auth.service.js";
import { analyticsProcessingWorker } from "./analytics-processing.worker.js";
import { analyticsFilterValueSchema } from "./analytics-query.schemas.js";
import { canonicalVisualizationTitle } from "./analytics-dashboard-reconciler.service.js";
import { createDashboardSpecificationSchema, type AnalyticsDashboardSpecification } from "./analytics-dashboard.schemas.js";
import type { AnalyticsSemanticModel } from "./analytics-semantic.schemas.js";

function integer(value: unknown, label: string) { if (typeof value !== "number" || !Number.isInteger(value) || value < 1) throw new ApiError(400, `${label} must be a positive integer`, "VALIDATION_ERROR"); return value; }
function reason(value: unknown) { if (typeof value !== "string" || value.trim().length < 10 || value.trim().length > 500) throw new ApiError(400, "Audit reason must be 10–500 characters", "VALIDATION_ERROR"); return value.trim().replace(/\s+/g," "); }
async function ownedDashboard(id: string, adminUserId: string) {
  const dashboard = await prisma.analyticsDashboard.findFirst({ where: { id, ownerAdminId: adminUserId, deletedAt: null }, include: { dataset: true, currentVersion: { include: { semanticModel: true } } } });
  if (!dashboard?.currentVersion?.semanticModel) throw new ApiError(404, "Analytics dashboard not found", "ANALYTICS_DASHBOARD_NOT_FOUND");
  return dashboard;
}
async function validationFor(dashboard: Awaited<ReturnType<typeof ownedDashboard>>) {
  const columns = await prisma.analyticsDatasetColumn.findMany({ where: { datasetId: dashboard.datasetId, sheetId: dashboard.dataset.activeSheetId! }, select: { normalizedName: true } });
  return createDashboardSpecificationSchema({ semanticModel: dashboard.currentVersion!.semanticModel!.semanticModel as unknown as AnalyticsSemanticModel, allFields: columns.map((item) => item.normalizedName) });
}
function validationMessage(error: { issues: Array<{ path: PropertyKey[]; message: string }> }) { return error.issues.slice(0,10).map((item)=>`${item.path.join(".")||"specification"}: ${item.message}`).join("; "); }
async function createChildren(transaction: Prisma.TransactionClient, versionId: string, specification: AnalyticsDashboardSpecification, source: "AI"|"FALLBACK") {
  await transaction.analyticsDashboardVisualization.createMany({ data: specification.visualizations.map((item,index)=>({ dashboardVersionId:versionId,widgetKey:item.id,type:item.type,title:item.title,dimensionField:item.dimension,measureField:item.measure,aggregation:item.aggregation,configuration:{description:item.description,secondaryMeasure:item.secondaryMeasure,stackBy:item.stackBy,columns:item.columns,limit:item.limit,timeGrain:item.timeGrain,sort:item.sort,topN:item.topN,showOther:item.showOther,formatOverride:item.formatOverride},layout:item.layout,visible:item.visible,sortOrder:index })) });
  await transaction.analyticsDashboardFilter.createMany({ data: specification.filters.map((item,index)=>({dashboardVersionId:versionId,filterKey:item.id,field:item.field,type:item.type,operator:null,configuration:{},sortOrder:index})) });
  await transaction.analyticsDashboardInsight.createMany({ data: specification.insights.map((item,index)=>({dashboardVersionId:versionId,content:`${item.title}: ${item.content}`,source,evidence:item.evidence,confidence:item.confidence,sortOrder:index})) });
}
export async function listDashboards(adminUserId: string, input: {page?:unknown;pageSize?:unknown}={}) {
  const page=typeof input.page==='string'?Number(input.page):typeof input.page==='number'?input.page:1; const pageSize=typeof input.pageSize==='string'?Number(input.pageSize):typeof input.pageSize==='number'?input.pageSize:20;
  if(!Number.isInteger(page)||page<1||!Number.isInteger(pageSize)||pageSize<1||pageSize>100)throw new ApiError(400,"Invalid pagination","VALIDATION_ERROR");
  const where={ownerAdminId:adminUserId,deletedAt:null}; const [items,total]=await Promise.all([prisma.analyticsDashboard.findMany({where,include:{dataset:{select:{id:true,name:true,status:true,rowCount:true,columnCount:true}},currentVersion:{select:{id:true,version:true,source:true,visualizationCount:true,createdAt:true}},_count:{select:{versions:true}}},orderBy:{updatedAt:'desc'},skip:(page-1)*pageSize,take:pageSize}),prisma.analyticsDashboard.count({where})]);
  return {dashboards:items.map(({_count,...item})=>({...item,versionCount:_count.versions})),pagination:{page,pageSize,total,totalPages:Math.max(1,Math.ceil(total/pageSize))}};
}
export async function getDashboard(id:string,adminUserId:string){
  const dashboard=await ownedDashboard(id,adminUserId); const version=await prisma.analyticsDashboardVersion.findUniqueOrThrow({where:{id:dashboard.currentVersionId!},include:{visualizations:{orderBy:{sortOrder:'asc'}},filters:{orderBy:{sortOrder:'asc'}},insights:{orderBy:{sortOrder:'asc'}}}}); const columns=await prisma.analyticsDatasetColumn.findMany({where:{datasetId:dashboard.datasetId,sheetId:dashboard.dataset.activeSheetId!},select:{normalizedName:true,displayName:true,dataType:true,semanticType:true,uniqueCount:true,nullPercentage:true},orderBy:{ordinal:'asc'}});
  return {dashboard:{id:dashboard.id,title:dashboard.title,description:dashboard.description,status:dashboard.status,datasetId:dashboard.datasetId,createdAt:dashboard.createdAt,updatedAt:dashboard.updatedAt,dataset:{id:dashboard.dataset.id,name:dashboard.dataset.name,rowCount:dashboard.dataset.rowCount,columnCount:dashboard.dataset.columnCount,datasetVersion:dashboard.dataset.datasetVersion},currentVersion:version,specification:version.specification,columns,semanticModel:dashboard.currentVersion!.semanticModel!.semanticModel}};
}
export async function saveDashboard(id:string,adminUserId:string,input:{baseVersion?:unknown;specification?:unknown;filterState?:unknown;changeSummary?:unknown},context:AdminRequestContext){
  const dashboard=await ownedDashboard(id,adminUserId); const baseVersion=integer(input.baseVersion,"Base version"); if(dashboard.currentVersion!.version!==baseVersion)throw new ApiError(409,"Dashboard was updated in another session","ANALYTICS_DASHBOARD_VERSION_CONFLICT"); const schema=await validationFor(dashboard); const parsed=schema.safeParse(input.specification); if(!parsed.success)throw new ApiError(400,validationMessage(parsed.error),"ANALYTICS_DASHBOARD_SPEC_INVALID"); const semantic=dashboard.currentVersion!.semanticModel!.semanticModel as unknown as AnalyticsSemanticModel; const specification={...parsed.data,visualizations:parsed.data.visualizations.map(item=>({...item,title:canonicalVisualizationTitle(semantic,item)}))}; const parsedFilters=analyticsFilterValueSchema.array().max(20).safeParse(input.filterState??[]);if(!parsedFilters.success)throw new ApiError(400,validationMessage(parsedFilters.error),"ANALYTICS_FILTER_STATE_INVALID"); const changeSummary=typeof input.changeSummary==='string'&&input.changeSummary.trim()?input.changeSummary.trim().slice(0,500):"Dashboard configuration updated"; const next=baseVersion+1;
  return prisma.$transaction(async transaction=>{const version=await transaction.analyticsDashboardVersion.create({data:{dashboardId:id,semanticModelId:dashboard.currentVersion!.semanticModelId,datasetVersion:dashboard.dataset.datasetVersion,version:next,source:'USER_EDIT',schemaVersion:specification.schemaVersion,specification:specification,filterState:parsedFilters.data,layoutState:Object.fromEntries(specification.visualizations.map(item=>[item.id,item.layout])),visualizationState:specification.visualizations,insightState:specification.insights,generationMetadata:{operation:'user_edit',baseVersion},visualizationCount:specification.visualizations.length,changeSummary,createdByAdminId:adminUserId}}); await createChildren(transaction,version.id,specification,'FALLBACK'); await transaction.analyticsDashboard.update({where:{id},data:{title:specification.title,description:specification.description,currentVersionId:version.id}}); await transaction.adminAuditLog.create({data:{adminUserId,action:'ANALYTICS_DASHBOARD_UPDATED',resourceType:'AnalyticsDashboard',resourceId:id,metadata:{previousVersion:baseVersion,newVersion:next,changeSummary},ipAddress:context.ipAddress??null,userAgent:context.userAgent??null}});return {dashboardId:id,version:next,specification:specification};});
}
export async function duplicateDashboard(id:string,adminUserId:string,context:AdminRequestContext){const source=await ownedDashboard(id,adminUserId);const spec=source.currentVersion!.specification as unknown as AnalyticsDashboardSpecification;return prisma.$transaction(async transaction=>{const copy=await transaction.analyticsDashboard.create({data:{datasetId:source.datasetId,ownerAdminId:adminUserId,title:`${source.title} Copy`.slice(0,160),description:source.description,status:'READY'}});const version=await transaction.analyticsDashboardVersion.create({data:{dashboardId:copy.id,semanticModelId:source.currentVersion!.semanticModelId,datasetVersion:source.currentVersion!.datasetVersion,version:1,source:'USER_EDIT',schemaVersion:1,specification:{...spec,title:`${source.title} Copy`.slice(0,160)},filterState:(Array.isArray(source.currentVersion!.filterState)?source.currentVersion!.filterState:[]) as Prisma.InputJsonValue,layoutState:Object.fromEntries(spec.visualizations.map(item=>[item.id,item.layout])),visualizationState:spec.visualizations,insightState:spec.insights,generationMetadata:{operation:'duplicate',sourceDashboardId:id,sourceVersion:source.currentVersion!.version},visualizationCount:spec.visualizations.length,changeSummary:'Dashboard duplicated',createdByAdminId:adminUserId}});await createChildren(transaction,version.id,{...spec,title:`${source.title} Copy`.slice(0,160)},'FALLBACK');await transaction.analyticsDashboard.update({where:{id:copy.id},data:{currentVersionId:version.id}});await transaction.adminAuditLog.create({data:{adminUserId,action:'ANALYTICS_DASHBOARD_DUPLICATED',resourceType:'AnalyticsDashboard',resourceId:copy.id,metadata:{sourceDashboardId:id},ipAddress:context.ipAddress??null,userAgent:context.userAgent??null}});return {dashboardId:copy.id};});}
export async function deleteDashboard(id:string,adminUserId:string,reasonValue:unknown,context:AdminRequestContext){const dashboard=await ownedDashboard(id,adminUserId);const auditReason=reason(reasonValue);const deletedAt=new Date();await prisma.$transaction([prisma.analyticsDashboard.update({where:{id},data:{status:'ARCHIVED',deletedAt}}),prisma.adminAuditLog.create({data:{adminUserId,action:'ANALYTICS_DASHBOARD_DELETED',resourceType:'AnalyticsDashboard',resourceId:id,metadata:{reason:auditReason,currentVersion:dashboard.currentVersion!.version},ipAddress:context.ipAddress??null,userAgent:context.userAgent??null}})]);return{deleted:true,dashboardId:id,deletedAt};}
export async function requestRegeneration(id:string,adminUserId:string,context:AdminRequestContext){const dashboard=await ownedDashboard(id,adminUserId);if(analyticsProcessingWorker.isRunning(dashboard.datasetId))throw new ApiError(409,"Dataset processing is already running","ANALYTICS_PROCESSING_IN_PROGRESS");await prisma.$transaction([prisma.analyticsDataset.update({where:{id:dashboard.datasetId},data:{status:'GENERATING',processingStage:'DASHBOARD_PLANNING',processingMessage:'Dashboard regeneration queued',processingHeartbeatAt:new Date()}}),prisma.adminAuditLog.create({data:{adminUserId,action:'ANALYTICS_DASHBOARD_REGENERATION_REQUESTED',resourceType:'AnalyticsDashboard',resourceId:id,metadata:{currentVersion:dashboard.currentVersion!.version,semanticModelVersion:dashboard.dataset.semanticModelVersion},ipAddress:context.ipAddress??null,userAgent:context.userAgent??null}})]);analyticsProcessingWorker.enqueueDashboard(dashboard.datasetId,id);return{accepted:true,dashboardId:id,status:'GENERATING'};}
