import { ROLE_PERMISSIONS, type AdminRole } from "../../config/admin-permissions.js";
import { prisma } from "../../database/prisma.js";
import { getPortfolioSummary, getRecentPortfolioAccounts } from "../portfolio/portfolio.service.js";
function getAccessSummary(role:AdminRole){return{role,permissions:ROLE_PERMISSIONS[role],operationalModulesEnabled:true,enabledModules:["dashboard","customers","portfolio","inventory","tickets","payments","audit","admins","sessions","settings","business_data","analytics"]}}
function startOfCurrentMonthInIndia(){const offset=330*60*1000;const india=new Date(Date.now()+offset);return new Date(Date.UTC(india.getUTCFullYear(),india.getUTCMonth(),1)-offset)}
async function getMetrics(){const monthStart=startOfCurrentMonthInIndia();const[totalCustomers,customerStatusGroups,newCustomers,totalAssets,assignedAssets,unassignedAssets,lockedAssets,subscriptionGroups,ticketGroups,monthlyPayments,monthlyPaymentCount,recentCustomers,portfolio,portfolioRecent]=await Promise.all([
prisma.user.count(),prisma.user.groupBy({by:["accountStatus"],_count:{_all:true}}),prisma.user.count({where:{createdAt:{gte:monthStart}}}),prisma.asset.count(),prisma.asset.count({where:{userId:{not:null}}}),prisma.asset.count({where:{userId:null}}),prisma.asset.count({where:{status:"locked"}}),prisma.subscription.groupBy({by:["status"],_count:{_all:true}}),prisma.supportTicket.groupBy({by:["status","priority"],_count:{_all:true}}),prisma.transaction.aggregate({where:{type:"PAYMENT",direction:"CREDIT",status:"completed",transactionDate:{gte:monthStart}},_sum:{amount:true}}),prisma.transaction.count({where:{type:"PAYMENT",direction:"CREDIT",status:"completed",transactionDate:{gte:monthStart}}}),prisma.user.findMany({orderBy:{createdAt:"desc"},take:5,select:{id:true,name:true,phone:true,accountStatus:true,lastLoginAt:true,lastActivityAt:true,createdAt:true,_count:{select:{assets:true,portfolioAccounts:true}}}}),getPortfolioSummary(),getRecentPortfolioAccounts(5)]);
const customerStatuses=Object.fromEntries(customerStatusGroups.map(group=>[group.accountStatus,group._count._all]));const subscriptions=Object.fromEntries(subscriptionGroups.map(group=>[group.status,group._count._all]));const tickets={open:0,inProgress:0,resolved:0,closed:0,highPriority:0};for(const group of ticketGroups){if(group.status==="open")tickets.open+=group._count._all;if(group.status==="in_progress")tickets.inProgress+=group._count._all;if(group.status==="resolved")tickets.resolved+=group._count._all;if(group.status==="closed")tickets.closed+=group._count._all;if(["high","critical"].includes(group.priority)&&!["resolved","closed"].includes(group.status))tickets.highPriority+=group._count._all}
return{generatedAt:new Date(),customers:{total:totalCustomers,active:customerStatuses.active??0,suspended:customerStatuses.suspended??0,closed:customerStatuses.closed??0,newThisMonth:newCustomers},assets:{total:totalAssets,assigned:assignedAssets,unassigned:unassignedAssets,locked:lockedAssets},subscriptions:{total:Object.values(subscriptions).reduce((sum,value)=>sum+Number(value),0),active:subscriptions.active??0,closed:subscriptions.closed??0},activeSubscriptions:subscriptions.active??0,tickets,openTickets:tickets.open+tickets.inProgress,paymentsThisMonth:{count:monthlyPaymentCount,amount:Math.round(Number(monthlyPayments._sum.amount??0)*100)/100,startsAt:monthStart},recentCustomers,portfolio:{...portfolio,recentAccounts:portfolioRecent}}}
export const adminDashboardService={getAccessSummary,getMetrics};
