export interface ZohoInvoiceRecord { invoiceId:string; customerNumber:string; invoiceDate:string; invoiceAmount:number; amountPaid:number; balanceDue:number; paymentStatus?:string|null }
export interface SynoriqReceiptRecord { receiptId:string; sourceApplicationNumber:string; receiptDate:string; amountReceived:number; paymentMode?:string|null; receiptStatus?:string|null }
interface ReconciliationDetail{accountKey:string;invoiceAmount:number;amountPaid:number;balanceDue:number;amountReceived:number;variance:number;classification:string;priority:string;recommendedAction:string;invoiceCount:number;receiptCount:number;duplicateInvoiceIds:number;duplicateReceiptIds:number;paymentModes:Record<string,number>;allocations:Array<{receiptId:string;invoiceId:string|null;amount:number}>}
function key(value:string){return value.trim().replace(/\s+/g," ").toUpperCase()}
export function reconcileZohoSynoriq(input:{invoices:ZohoInvoiceRecord[];receipts:SynoriqReceiptRecord[];tolerance?:number}){
  const tolerance=input.tolerance??1;if(!Number.isFinite(tolerance)||tolerance<0)throw new Error("Reconciliation tolerance must be a non-negative number");
  const invoicesBy=new Map<string,ZohoInvoiceRecord[]>(),receiptsBy=new Map<string,SynoriqReceiptRecord[]>();
  for(const invoice of input.invoices){const normalized=key(invoice.customerNumber);invoicesBy.set(normalized,[...(invoicesBy.get(normalized)??[]),invoice])}
  for(const receipt of input.receipts){const normalized=key(receipt.sourceApplicationNumber);receiptsBy.set(normalized,[...(receiptsBy.get(normalized)??[]),receipt])}
  const accountKeys=new Set([...invoicesBy.keys(),...receiptsBy.keys()]);const details:ReconciliationDetail[]=[];
  for(const accountKey of accountKeys){
    const invoices=[...(invoicesBy.get(accountKey)??[])].sort((a,b)=>a.invoiceDate.localeCompare(b.invoiceDate));
    const receipts=[...(receiptsBy.get(accountKey)??[])].sort((a,b)=>a.receiptDate.localeCompare(b.receiptDate));
    const invoiceAmount=invoices.reduce((sum,item)=>sum+item.invoiceAmount,0),amountPaid=invoices.reduce((sum,item)=>sum+item.amountPaid,0),balanceDue=invoices.reduce((sum,item)=>sum+item.balanceDue,0),amountReceived=receipts.reduce((sum,item)=>sum+item.amountReceived,0),variance=amountPaid-amountReceived;
    const classification=!invoices.length?"NO_ZOHO_INVOICE":!receipts.length?"NO_SYNORIQ_RECEIPT":Math.abs(variance)<=tolerance?"MATCHED":variance>0?"ZOHO_PAID_GREATER":"SYNORIQ_RECEIVED_GREATER";
    const priority=classification==="MATCHED"?"LOW":!invoices.length||!receipts.length?"HIGH":Math.abs(variance)>Math.max(1000,tolerance*10)?"HIGH":"MEDIUM";
    const allocations:Array<{receiptId:string;invoiceId:string|null;amount:number}>=[];const remaining=invoices.map(item=>({invoiceId:item.invoiceId,remaining:Math.max(0,item.invoiceAmount)}));
    for(const receipt of receipts){let unallocated=receipt.amountReceived;for(const invoice of remaining){if(unallocated<=0)break;const amount=Math.min(unallocated,invoice.remaining);if(amount>0){allocations.push({receiptId:receipt.receiptId,invoiceId:invoice.invoiceId,amount});invoice.remaining-=amount;unallocated-=amount}}if(unallocated>0)allocations.push({receiptId:receipt.receiptId,invoiceId:null,amount:unallocated})}
    details.push({accountKey,invoiceAmount,amountPaid,balanceDue,amountReceived,variance,classification,priority,recommendedAction:classification==="MATCHED"?"No action":classification==="NO_SYNORIQ_RECEIPT"?"Locate or post the missing receipt":classification==="NO_ZOHO_INVOICE"?"Locate or create the corresponding invoice":"Review payment allocation and posting dates",invoiceCount:invoices.length,receiptCount:receipts.length,duplicateInvoiceIds:invoices.length-new Set(invoices.map(item=>item.invoiceId)).size,duplicateReceiptIds:receipts.length-new Set(receipts.map(item=>item.receiptId)).size,paymentModes:Object.fromEntries([...new Set(receipts.map(item=>item.paymentMode??"UNKNOWN"))].map(mode=>[mode,receipts.filter(item=>(item.paymentMode??"UNKNOWN")===mode).length])),allocations});
  }
  const count=(classification:string)=>details.filter(item=>item.classification===classification).length;const rank:Record<string,number>={HIGH:0,MEDIUM:1,LOW:2};
  return{tolerance,summary:{accounts:details.length,matched:count("MATCHED"),zohoPaidGreater:count("ZOHO_PAID_GREATER"),synoriqReceivedGreater:count("SYNORIQ_RECEIVED_GREATER"),noSynoriqReceipt:count("NO_SYNORIQ_RECEIPT"),noZohoInvoice:count("NO_ZOHO_INVOICE"),invoiceAmount:details.reduce((sum,item)=>sum+item.invoiceAmount,0),amountPaid:details.reduce((sum,item)=>sum+item.amountPaid,0),balanceDue:details.reduce((sum,item)=>sum+item.balanceDue,0),amountReceived:details.reduce((sum,item)=>sum+item.amountReceived,0),variance:details.reduce((sum,item)=>sum+item.variance,0)},details:details.sort((a,b)=>(rank[a.priority]??9)-(rank[b.priority]??9)||Math.abs(b.variance)-Math.abs(a.variance))};
}
